//
// auto-generated by op2.py
//

void diff_flux_omp4_kernel(
  int *data0,
  int dat0size,
  int *map1,
  int map1size,
  double *data1,
  int dat1size,
  double *data3,
  int dat3size,
  double *data5,
  int dat5size,
  double *data7,
  int dat7size,
  double *data9,
  int dat9size,
  double *data11,
  int dat11size,
  double *data13,
  int dat13size,
  double *data15,
  int dat15size,
  int *col_reord,
  int set_size1,
  int start,
  int end,
  int num_teams,
  int nthread){

  #pragma omp target teams num_teams(num_teams) thread_limit(nthread) map(to:data0[0:dat0size]) \
    map(to: gaussW_g_ompkernel[:7])\
    map(to:col_reord[0:set_size1],map1[0:map1size],data1[0:dat1size],data3[0:dat3size],data5[0:dat5size],data7[0:dat7size],data9[0:dat9size],data11[0:dat11size],data13[0:dat13size],data15[0:dat15size])
  #pragma omp distribute parallel for schedule(static,1)
  for ( int e=start; e<end; e++ ){
    int n_op = col_reord[e];
    int map1idx;
    int map2idx;
    map1idx = map1[n_op + set_size1 * 0];
    map2idx = map1[n_op + set_size1 * 1];

    const double* arg1_vec[] = {
       &data1[3 * map1idx],
       &data1[3 * map2idx]};
    const double* arg3_vec[] = {
       &data3[3 * map1idx],
       &data3[3 * map2idx]};
    const double* arg5_vec[] = {
       &data5[21 * map1idx],
       &data5[21 * map2idx]};
    const double* arg7_vec[] = {
       &data7[21 * map1idx],
       &data7[21 * map2idx]};
    const double* arg9_vec[] = {
       &data9[21 * map1idx],
       &data9[21 * map2idx]};
    const double* arg11_vec[] = {
       &data11[21 * map1idx],
       &data11[21 * map2idx]};
    const double* arg13_vec[] = {
       &data13[21 * map1idx],
       &data13[21 * map2idx]};
    double* arg15_vec[] = {
       &data15[21 * map1idx],
       &data15[21 * map2idx]};
    //variable mapping
    const int *edgeNum = &data0[2*n_op];
    const double **x = arg1_vec;
    const double **y = arg3_vec;
    const double **sJ = arg5_vec;
    const double **nx = arg7_vec;
    const double **ny = arg9_vec;
    const double **sigX = arg11_vec;
    const double **sigY = arg13_vec;
    double **flux = arg15_vec;

    //inline function
    

    int edgeL = edgeNum[0];
    int edgeR = edgeNum[1];
    bool reverse;

    if(edgeR == 0) {
      if(edgeL == 0) {
        reverse = !(x[0][0] == x[1][0] && y[0][0] == y[1][0]);
      } else if(edgeL == 1) {
        reverse = !(x[0][1] == x[1][0] && y[0][1] == y[1][0]);
      } else {
        reverse = !(x[0][2] == x[1][0] && y[0][2] == y[1][0]);
      }
    } else if(edgeR == 1) {
      if(edgeL == 0) {
        reverse = !(x[0][0] == x[1][1] && y[0][0] == y[1][1]);
      } else if(edgeL == 1) {
        reverse = !(x[0][1] == x[1][1] && y[0][1] == y[1][1]);
      } else {
        reverse = !(x[0][2] == x[1][1] && y[0][2] == y[1][1]);
      }
    } else {
      if(edgeL == 0) {
        reverse = !(x[0][0] == x[1][2] && y[0][0] == y[1][2]);
      } else if(edgeL == 1) {
        reverse = !(x[0][1] == x[1][2] && y[0][1] == y[1][2]);
      } else {
        reverse = !(x[0][2] == x[1][2] && y[0][2] == y[1][2]);
      }
    }

    int exIndL = 0;
    if(edgeL == 1) exIndL = 7;
    else if(edgeL == 2) exIndL = 2 * 7;

    int exIndR = 0;
    if(edgeR == 1) exIndR = 7;
    else if(edgeR == 2) exIndR = 2 * 7;

    for(int i = 0; i < 7; i++) {
      int rInd;
      int lInd = exIndL + i;
      if(reverse) {
        rInd = exIndR + 7 - i - 1;
      } else {
        rInd = exIndR + i;
      }

      double sigFX = (sigX[0][lInd] + sigX[1][rInd]) / 2.0;
      double sigFY = (sigY[0][lInd] + sigY[1][rInd]) / 2.0;

      flux[0][lInd] += gaussW_g_ompkernel[i] * sJ[0][lInd] * (nx[0][lInd] * sigFX + ny[0][lInd] * sigFY);
    }

    for(int i = 0; i < 7; i++) {
      int lInd;
      int rInd = exIndR + i;
      if(reverse) {
        lInd = exIndL + 7 - i - 1;
      } else {
        lInd = exIndL + i;
      }

      double sigFX = (sigX[0][lInd] + sigX[1][rInd]) / 2.0;
      double sigFY = (sigY[0][lInd] + sigY[1][rInd]) / 2.0;

      flux[1][rInd] += gaussW_g_ompkernel[i] * sJ[1][rInd] * (nx[1][rInd] * sigFX + ny[1][rInd] * sigFY);
    }
    //end inline func
  }

}
