//
// auto-generated by op2.py
//

void pressure_rhs_omp4_kernel(
  double *arg0,
  double *arg1,
  double *arg2,
  double *arg3,
  double *data4,
  int dat4size,
  double *data5,
  int dat5size,
  double *data6,
  int dat6size,
  double *data7,
  int dat7size,
  double *data8,
  int dat8size,
  int count,
  int num_teams,
  int nthread){

  double arg0_l = *arg0;
  double arg1_l = *arg1;
  double arg2_l = *arg2;
  double arg3_l = *arg3;
  #pragma omp target teams num_teams(num_teams) thread_limit(nthread) map(to:data4[0:dat4size],data5[0:dat5size],data6[0:dat6size],data7[0:dat7size],data8[0:dat8size])
  #pragma omp distribute parallel for schedule(static,1)
  for ( int n_op=0; n_op<count; n_op++ ){
    //variable mapping
    const double *b0 = &arg0_l;
    const double *b1 = &arg1_l;
    const double *g0 = &arg2_l;
    const double *dt = &arg3_l;
    const double *J = &data4[15*n_op];
    const double *sJ = &data5[15*n_op];
    const double *dPdN = &data6[15*n_op];
    double *dPdNOld = &data7[15*n_op];
    double *divVelT = &data8[15*n_op];

    //inline function
    
    double factor = (*g0) / (*dt);
    for(int i = 0; i < 15; i++) {
      divVelT[i] = J[i] * (-divVelT[i] * factor);
      dPdNOld[i] = sJ[i] * ((*b0) * dPdN[i] + (*b1) * dPdNOld[i]);
    }
    //end inline func
  }

  *arg0 = arg0_l;
  *arg1 = arg1_l;
  *arg2 = arg2_l;
  *arg3 = arg3_l;
}
