//
// auto-generated by op2.py
//

#include "cblas.h"

#include  "op_lib_cpp.h"

//
// op_par_loop declarations
//
#ifdef OPENACC
#ifdef __cplusplus
extern "C" {
#endif
#endif
#ifdef OPENACC
#ifdef __cplusplus
}
#endif
#endif

#include "../blas_calls.h"

inline void openblas_viscosity_rhs(const int numCells, const double *mm, const double *qtt0,
                                   const double *qtt1, double *vis0, double *vis1) {
  // cblas_dgemm(CblasColMajor, CblasTrans, CblasNoTrans, 15, numCells, 15, 1.0, visMat, 15, qtt0, 15, 0.0, temp0, 15);
  // cblas_dgemm(CblasColMajor, CblasTrans, CblasNoTrans, 15, numCells, 15, 1.0, visMat, 15, qtt1, 15, 0.0, temp1, 15);

  cblas_dgemm(CblasColMajor, CblasTrans, CblasNoTrans, 15, numCells, 15, 1.0, MASS, 15, qtt0, 15, 0.0, vis0, 15);
  cblas_dgemm(CblasColMajor, CblasTrans, CblasNoTrans, 15, numCells, 15, 1.0, MASS, 15, qtt1, 15, 0.0, vis1, 15);

  // for(int i = 0; i < numCells; i++) {
  //   const double *mm_c = mm + i * 15 * 15;
  //   const double *qtt0_c = qtt0 + i * 15;
  //   const double *qtt1_c = qtt1 + i * 15;
  //   double *vis0_c = vis0 + i * 15;
  //   double *vis1_c = vis1 + i * 15;
  //
  //   cblas_dgemv(CblasColMajor, CblasNoTrans, 15, 15, 1.0, mm_c, 15, qtt0_c, 1, 0.0, vis0_c, 1);
  //   cblas_dgemv(CblasColMajor, CblasNoTrans, 15, 15, 1.0, mm_c, 15, qtt1_c, 1, 0.0, vis1_c, 1);
  // }
}

void viscosity_rhs_blas(INSData *nsData, CubatureData *cubatureData) {
  op_dat QTT0 = op_decl_dat_hdf5(nsData->cells, 15, "double", "../../../res.h5", "QTT0");
  op_dat QTT1 = op_decl_dat_hdf5(nsData->cells, 15, "double", "../../../res.h5", "QTT1");
  // Make sure OP2 data is in the right place
  op_arg viscosity_rhs_args[] = {
    op_arg_dat(cubatureData->mm, -1, OP_ID, 15 * 15, "double", OP_READ),
    op_arg_dat(QTT0, -1, OP_ID, 15, "double", OP_READ),
    op_arg_dat(QTT1, -1, OP_ID, 15, "double", OP_READ),
    op_arg_dat(nsData->visRHS[0], -1, OP_ID, 15, "double", OP_WRITE),
    op_arg_dat(nsData->visRHS[1], -1, OP_ID, 15, "double", OP_WRITE)
  };
  op_mpi_halo_exchanges(nsData->cells, 5, viscosity_rhs_args);

  openblas_viscosity_rhs(nsData->numCells, (double *)cubatureData->mm->data, (double *)QTT0->data,
                      (double *)QTT1->data, (double *)nsData->visRHS[0]->data,
                      (double *)nsData->visRHS[1]->data);

  // Set correct dirty bits for OP2
  op_mpi_set_dirtybit(5, viscosity_rhs_args);
}
