//
// auto-generated by op2.py
//

//user function
__device__ void gauss_grad_faces_gpu( const int *edgeNum, const double **mDx0,
                             const double **mDy0, const double **mDx1,
                             const double **mDy1, const double **mDx2,
                             const double **mDy2, double **pDx0, double **pDy0,
                             double **pDx1, double **pDy1, double **pDx2,
                             double **pDy2) {

  int edgeL = edgeNum[0];
  int edgeR = edgeNum[1];

  for(int m = 0; m < 7; m++) {
    for(int n = 0; n < 15; n++) {
      int indL = m * 15 + n;
      int indR = m * 15 + n;

      if(edgeL == 0) {
        if(edgeR == 0) {
          pDx0[0][indL] += mDx0[1][indR];
          pDy0[0][indL] += mDy0[1][indR];
          pDx0[1][indR] += mDx0[0][indL];
          pDy0[1][indR] += mDy0[0][indL];
        } else if(edgeR == 1) {
          pDx0[0][indL] += mDx1[1][indR];
          pDy0[0][indL] += mDy1[1][indR];
          pDx1[1][indR] += mDx0[0][indL];
          pDy1[1][indR] += mDy0[0][indL];
        } else {
          pDx0[0][indL] += mDx2[1][indR];
          pDy0[0][indL] += mDy2[1][indR];
          pDx2[1][indR] += mDx0[0][indL];
          pDy2[1][indR] += mDy0[0][indL];
        }
      } else if(edgeL == 1) {
        if(edgeR == 0) {
          pDx1[0][indL] += mDx0[1][indR];
          pDy1[0][indL] += mDy0[1][indR];
          pDx0[1][indR] += mDx1[0][indL];
          pDy0[1][indR] += mDy1[0][indL];
        } else if(edgeR == 1) {
          pDx1[0][indL] += mDx1[1][indR];
          pDy1[0][indL] += mDy1[1][indR];
          pDx1[1][indR] += mDx1[0][indL];
          pDy1[1][indR] += mDy1[0][indL];
        } else {
          pDx1[0][indL] += mDx2[1][indR];
          pDy1[0][indL] += mDy2[1][indR];
          pDx2[1][indR] += mDx1[0][indL];
          pDy2[1][indR] += mDy1[0][indL];
        }
      } else {
        if(edgeR == 0) {
          pDx2[0][indL] += mDx0[1][indR];
          pDy2[0][indL] += mDy0[1][indR];
          pDx0[1][indR] += mDx2[0][indL];
          pDy0[1][indR] += mDy2[0][indL];
        } else if(edgeR == 1) {
          pDx2[0][indL] += mDx1[1][indR];
          pDy2[0][indL] += mDy1[1][indR];
          pDx1[1][indR] += mDx2[0][indL];
          pDy1[1][indR] += mDy2[0][indL];
        } else {
          pDx2[0][indL] += mDx2[1][indR];
          pDy2[0][indL] += mDy2[1][indR];
          pDx2[1][indR] += mDx2[0][indL];
          pDy2[1][indR] += mDy2[0][indL];
        }
      }
    }
  }

}

// CUDA kernel function
__global__ void op_cuda_gauss_grad_faces(
  const double *__restrict ind_arg0,
  const double *__restrict ind_arg1,
  const double *__restrict ind_arg2,
  const double *__restrict ind_arg3,
  const double *__restrict ind_arg4,
  const double *__restrict ind_arg5,
  double *__restrict ind_arg6,
  double *__restrict ind_arg7,
  double *__restrict ind_arg8,
  double *__restrict ind_arg9,
  double *__restrict ind_arg10,
  double *__restrict ind_arg11,
  const int *__restrict opDat1Map,
  const int *__restrict arg0,
  int start,
  int end,
  int   set_size) {
  double arg13_l[105];
  double arg14_l[105];
  double arg15_l[105];
  double arg16_l[105];
  double arg17_l[105];
  double arg18_l[105];
  double arg19_l[105];
  double arg20_l[105];
  double arg21_l[105];
  double arg22_l[105];
  double arg23_l[105];
  double arg24_l[105];
  double *arg13_vec[2] = {
    arg13_l,
    arg14_l,
  };
  double *arg15_vec[2] = {
    arg15_l,
    arg16_l,
  };
  double *arg17_vec[2] = {
    arg17_l,
    arg18_l,
  };
  double *arg19_vec[2] = {
    arg19_l,
    arg20_l,
  };
  double *arg21_vec[2] = {
    arg21_l,
    arg22_l,
  };
  double *arg23_vec[2] = {
    arg23_l,
    arg24_l,
  };
  int tid = threadIdx.x + blockIdx.x * blockDim.x;
  if (tid + start < end) {
    int n = tid + start;
    //initialise local variables
    double arg13_l[105];
    for ( int d=0; d<105; d++ ){
      arg13_l[d] = ZERO_double;
    }
    double arg14_l[105];
    for ( int d=0; d<105; d++ ){
      arg14_l[d] = ZERO_double;
    }
    double arg15_l[105];
    for ( int d=0; d<105; d++ ){
      arg15_l[d] = ZERO_double;
    }
    double arg16_l[105];
    for ( int d=0; d<105; d++ ){
      arg16_l[d] = ZERO_double;
    }
    double arg17_l[105];
    for ( int d=0; d<105; d++ ){
      arg17_l[d] = ZERO_double;
    }
    double arg18_l[105];
    for ( int d=0; d<105; d++ ){
      arg18_l[d] = ZERO_double;
    }
    double arg19_l[105];
    for ( int d=0; d<105; d++ ){
      arg19_l[d] = ZERO_double;
    }
    double arg20_l[105];
    for ( int d=0; d<105; d++ ){
      arg20_l[d] = ZERO_double;
    }
    double arg21_l[105];
    for ( int d=0; d<105; d++ ){
      arg21_l[d] = ZERO_double;
    }
    double arg22_l[105];
    for ( int d=0; d<105; d++ ){
      arg22_l[d] = ZERO_double;
    }
    double arg23_l[105];
    for ( int d=0; d<105; d++ ){
      arg23_l[d] = ZERO_double;
    }
    double arg24_l[105];
    for ( int d=0; d<105; d++ ){
      arg24_l[d] = ZERO_double;
    }
    int map1idx;
    int map2idx;
    map1idx = opDat1Map[n + set_size * 0];
    map2idx = opDat1Map[n + set_size * 1];
    const double* arg1_vec[] = {
       &ind_arg0[105 * map1idx],
       &ind_arg0[105 * map2idx]};
    const double* arg3_vec[] = {
       &ind_arg1[105 * map1idx],
       &ind_arg1[105 * map2idx]};
    const double* arg5_vec[] = {
       &ind_arg2[105 * map1idx],
       &ind_arg2[105 * map2idx]};
    const double* arg7_vec[] = {
       &ind_arg3[105 * map1idx],
       &ind_arg3[105 * map2idx]};
    const double* arg9_vec[] = {
       &ind_arg4[105 * map1idx],
       &ind_arg4[105 * map2idx]};
    const double* arg11_vec[] = {
       &ind_arg5[105 * map1idx],
       &ind_arg5[105 * map2idx]};
    double* arg13_vec[] = {
       &ind_arg6[105 * map1idx],
       &ind_arg6[105 * map2idx]};
    double* arg15_vec[] = {
       &ind_arg7[105 * map1idx],
       &ind_arg7[105 * map2idx]};
    double* arg17_vec[] = {
       &ind_arg8[105 * map1idx],
       &ind_arg8[105 * map2idx]};
    double* arg19_vec[] = {
       &ind_arg9[105 * map1idx],
       &ind_arg9[105 * map2idx]};
    double* arg21_vec[] = {
       &ind_arg10[105 * map1idx],
       &ind_arg10[105 * map2idx]};
    double* arg23_vec[] = {
       &ind_arg11[105 * map1idx],
       &ind_arg11[105 * map2idx]};

    //user-supplied kernel call
    gauss_grad_faces_gpu(arg0+n*2,
                     arg1_vec,
                     arg3_vec,
                     arg5_vec,
                     arg7_vec,
                     arg9_vec,
                     arg11_vec,
                     arg13_vec,
                     arg15_vec,
                     arg17_vec,
                     arg19_vec,
                     arg21_vec,
                     arg23_vec);
    atomicAdd(&ind_arg6[0+map1idx*105],arg13_l[0]);
    atomicAdd(&ind_arg6[1+map1idx*105],arg13_l[1]);
    atomicAdd(&ind_arg6[2+map1idx*105],arg13_l[2]);
    atomicAdd(&ind_arg6[3+map1idx*105],arg13_l[3]);
    atomicAdd(&ind_arg6[4+map1idx*105],arg13_l[4]);
    atomicAdd(&ind_arg6[5+map1idx*105],arg13_l[5]);
    atomicAdd(&ind_arg6[6+map1idx*105],arg13_l[6]);
    atomicAdd(&ind_arg6[7+map1idx*105],arg13_l[7]);
    atomicAdd(&ind_arg6[8+map1idx*105],arg13_l[8]);
    atomicAdd(&ind_arg6[9+map1idx*105],arg13_l[9]);
    atomicAdd(&ind_arg6[10+map1idx*105],arg13_l[10]);
    atomicAdd(&ind_arg6[11+map1idx*105],arg13_l[11]);
    atomicAdd(&ind_arg6[12+map1idx*105],arg13_l[12]);
    atomicAdd(&ind_arg6[13+map1idx*105],arg13_l[13]);
    atomicAdd(&ind_arg6[14+map1idx*105],arg13_l[14]);
    atomicAdd(&ind_arg6[15+map1idx*105],arg13_l[15]);
    atomicAdd(&ind_arg6[16+map1idx*105],arg13_l[16]);
    atomicAdd(&ind_arg6[17+map1idx*105],arg13_l[17]);
    atomicAdd(&ind_arg6[18+map1idx*105],arg13_l[18]);
    atomicAdd(&ind_arg6[19+map1idx*105],arg13_l[19]);
    atomicAdd(&ind_arg6[20+map1idx*105],arg13_l[20]);
    atomicAdd(&ind_arg6[21+map1idx*105],arg13_l[21]);
    atomicAdd(&ind_arg6[22+map1idx*105],arg13_l[22]);
    atomicAdd(&ind_arg6[23+map1idx*105],arg13_l[23]);
    atomicAdd(&ind_arg6[24+map1idx*105],arg13_l[24]);
    atomicAdd(&ind_arg6[25+map1idx*105],arg13_l[25]);
    atomicAdd(&ind_arg6[26+map1idx*105],arg13_l[26]);
    atomicAdd(&ind_arg6[27+map1idx*105],arg13_l[27]);
    atomicAdd(&ind_arg6[28+map1idx*105],arg13_l[28]);
    atomicAdd(&ind_arg6[29+map1idx*105],arg13_l[29]);
    atomicAdd(&ind_arg6[30+map1idx*105],arg13_l[30]);
    atomicAdd(&ind_arg6[31+map1idx*105],arg13_l[31]);
    atomicAdd(&ind_arg6[32+map1idx*105],arg13_l[32]);
    atomicAdd(&ind_arg6[33+map1idx*105],arg13_l[33]);
    atomicAdd(&ind_arg6[34+map1idx*105],arg13_l[34]);
    atomicAdd(&ind_arg6[35+map1idx*105],arg13_l[35]);
    atomicAdd(&ind_arg6[36+map1idx*105],arg13_l[36]);
    atomicAdd(&ind_arg6[37+map1idx*105],arg13_l[37]);
    atomicAdd(&ind_arg6[38+map1idx*105],arg13_l[38]);
    atomicAdd(&ind_arg6[39+map1idx*105],arg13_l[39]);
    atomicAdd(&ind_arg6[40+map1idx*105],arg13_l[40]);
    atomicAdd(&ind_arg6[41+map1idx*105],arg13_l[41]);
    atomicAdd(&ind_arg6[42+map1idx*105],arg13_l[42]);
    atomicAdd(&ind_arg6[43+map1idx*105],arg13_l[43]);
    atomicAdd(&ind_arg6[44+map1idx*105],arg13_l[44]);
    atomicAdd(&ind_arg6[45+map1idx*105],arg13_l[45]);
    atomicAdd(&ind_arg6[46+map1idx*105],arg13_l[46]);
    atomicAdd(&ind_arg6[47+map1idx*105],arg13_l[47]);
    atomicAdd(&ind_arg6[48+map1idx*105],arg13_l[48]);
    atomicAdd(&ind_arg6[49+map1idx*105],arg13_l[49]);
    atomicAdd(&ind_arg6[50+map1idx*105],arg13_l[50]);
    atomicAdd(&ind_arg6[51+map1idx*105],arg13_l[51]);
    atomicAdd(&ind_arg6[52+map1idx*105],arg13_l[52]);
    atomicAdd(&ind_arg6[53+map1idx*105],arg13_l[53]);
    atomicAdd(&ind_arg6[54+map1idx*105],arg13_l[54]);
    atomicAdd(&ind_arg6[55+map1idx*105],arg13_l[55]);
    atomicAdd(&ind_arg6[56+map1idx*105],arg13_l[56]);
    atomicAdd(&ind_arg6[57+map1idx*105],arg13_l[57]);
    atomicAdd(&ind_arg6[58+map1idx*105],arg13_l[58]);
    atomicAdd(&ind_arg6[59+map1idx*105],arg13_l[59]);
    atomicAdd(&ind_arg6[60+map1idx*105],arg13_l[60]);
    atomicAdd(&ind_arg6[61+map1idx*105],arg13_l[61]);
    atomicAdd(&ind_arg6[62+map1idx*105],arg13_l[62]);
    atomicAdd(&ind_arg6[63+map1idx*105],arg13_l[63]);
    atomicAdd(&ind_arg6[64+map1idx*105],arg13_l[64]);
    atomicAdd(&ind_arg6[65+map1idx*105],arg13_l[65]);
    atomicAdd(&ind_arg6[66+map1idx*105],arg13_l[66]);
    atomicAdd(&ind_arg6[67+map1idx*105],arg13_l[67]);
    atomicAdd(&ind_arg6[68+map1idx*105],arg13_l[68]);
    atomicAdd(&ind_arg6[69+map1idx*105],arg13_l[69]);
    atomicAdd(&ind_arg6[70+map1idx*105],arg13_l[70]);
    atomicAdd(&ind_arg6[71+map1idx*105],arg13_l[71]);
    atomicAdd(&ind_arg6[72+map1idx*105],arg13_l[72]);
    atomicAdd(&ind_arg6[73+map1idx*105],arg13_l[73]);
    atomicAdd(&ind_arg6[74+map1idx*105],arg13_l[74]);
    atomicAdd(&ind_arg6[75+map1idx*105],arg13_l[75]);
    atomicAdd(&ind_arg6[76+map1idx*105],arg13_l[76]);
    atomicAdd(&ind_arg6[77+map1idx*105],arg13_l[77]);
    atomicAdd(&ind_arg6[78+map1idx*105],arg13_l[78]);
    atomicAdd(&ind_arg6[79+map1idx*105],arg13_l[79]);
    atomicAdd(&ind_arg6[80+map1idx*105],arg13_l[80]);
    atomicAdd(&ind_arg6[81+map1idx*105],arg13_l[81]);
    atomicAdd(&ind_arg6[82+map1idx*105],arg13_l[82]);
    atomicAdd(&ind_arg6[83+map1idx*105],arg13_l[83]);
    atomicAdd(&ind_arg6[84+map1idx*105],arg13_l[84]);
    atomicAdd(&ind_arg6[85+map1idx*105],arg13_l[85]);
    atomicAdd(&ind_arg6[86+map1idx*105],arg13_l[86]);
    atomicAdd(&ind_arg6[87+map1idx*105],arg13_l[87]);
    atomicAdd(&ind_arg6[88+map1idx*105],arg13_l[88]);
    atomicAdd(&ind_arg6[89+map1idx*105],arg13_l[89]);
    atomicAdd(&ind_arg6[90+map1idx*105],arg13_l[90]);
    atomicAdd(&ind_arg6[91+map1idx*105],arg13_l[91]);
    atomicAdd(&ind_arg6[92+map1idx*105],arg13_l[92]);
    atomicAdd(&ind_arg6[93+map1idx*105],arg13_l[93]);
    atomicAdd(&ind_arg6[94+map1idx*105],arg13_l[94]);
    atomicAdd(&ind_arg6[95+map1idx*105],arg13_l[95]);
    atomicAdd(&ind_arg6[96+map1idx*105],arg13_l[96]);
    atomicAdd(&ind_arg6[97+map1idx*105],arg13_l[97]);
    atomicAdd(&ind_arg6[98+map1idx*105],arg13_l[98]);
    atomicAdd(&ind_arg6[99+map1idx*105],arg13_l[99]);
    atomicAdd(&ind_arg6[100+map1idx*105],arg13_l[100]);
    atomicAdd(&ind_arg6[101+map1idx*105],arg13_l[101]);
    atomicAdd(&ind_arg6[102+map1idx*105],arg13_l[102]);
    atomicAdd(&ind_arg6[103+map1idx*105],arg13_l[103]);
    atomicAdd(&ind_arg6[104+map1idx*105],arg13_l[104]);
    atomicAdd(&ind_arg6[0+map2idx*105],arg14_l[0]);
    atomicAdd(&ind_arg6[1+map2idx*105],arg14_l[1]);
    atomicAdd(&ind_arg6[2+map2idx*105],arg14_l[2]);
    atomicAdd(&ind_arg6[3+map2idx*105],arg14_l[3]);
    atomicAdd(&ind_arg6[4+map2idx*105],arg14_l[4]);
    atomicAdd(&ind_arg6[5+map2idx*105],arg14_l[5]);
    atomicAdd(&ind_arg6[6+map2idx*105],arg14_l[6]);
    atomicAdd(&ind_arg6[7+map2idx*105],arg14_l[7]);
    atomicAdd(&ind_arg6[8+map2idx*105],arg14_l[8]);
    atomicAdd(&ind_arg6[9+map2idx*105],arg14_l[9]);
    atomicAdd(&ind_arg6[10+map2idx*105],arg14_l[10]);
    atomicAdd(&ind_arg6[11+map2idx*105],arg14_l[11]);
    atomicAdd(&ind_arg6[12+map2idx*105],arg14_l[12]);
    atomicAdd(&ind_arg6[13+map2idx*105],arg14_l[13]);
    atomicAdd(&ind_arg6[14+map2idx*105],arg14_l[14]);
    atomicAdd(&ind_arg6[15+map2idx*105],arg14_l[15]);
    atomicAdd(&ind_arg6[16+map2idx*105],arg14_l[16]);
    atomicAdd(&ind_arg6[17+map2idx*105],arg14_l[17]);
    atomicAdd(&ind_arg6[18+map2idx*105],arg14_l[18]);
    atomicAdd(&ind_arg6[19+map2idx*105],arg14_l[19]);
    atomicAdd(&ind_arg6[20+map2idx*105],arg14_l[20]);
    atomicAdd(&ind_arg6[21+map2idx*105],arg14_l[21]);
    atomicAdd(&ind_arg6[22+map2idx*105],arg14_l[22]);
    atomicAdd(&ind_arg6[23+map2idx*105],arg14_l[23]);
    atomicAdd(&ind_arg6[24+map2idx*105],arg14_l[24]);
    atomicAdd(&ind_arg6[25+map2idx*105],arg14_l[25]);
    atomicAdd(&ind_arg6[26+map2idx*105],arg14_l[26]);
    atomicAdd(&ind_arg6[27+map2idx*105],arg14_l[27]);
    atomicAdd(&ind_arg6[28+map2idx*105],arg14_l[28]);
    atomicAdd(&ind_arg6[29+map2idx*105],arg14_l[29]);
    atomicAdd(&ind_arg6[30+map2idx*105],arg14_l[30]);
    atomicAdd(&ind_arg6[31+map2idx*105],arg14_l[31]);
    atomicAdd(&ind_arg6[32+map2idx*105],arg14_l[32]);
    atomicAdd(&ind_arg6[33+map2idx*105],arg14_l[33]);
    atomicAdd(&ind_arg6[34+map2idx*105],arg14_l[34]);
    atomicAdd(&ind_arg6[35+map2idx*105],arg14_l[35]);
    atomicAdd(&ind_arg6[36+map2idx*105],arg14_l[36]);
    atomicAdd(&ind_arg6[37+map2idx*105],arg14_l[37]);
    atomicAdd(&ind_arg6[38+map2idx*105],arg14_l[38]);
    atomicAdd(&ind_arg6[39+map2idx*105],arg14_l[39]);
    atomicAdd(&ind_arg6[40+map2idx*105],arg14_l[40]);
    atomicAdd(&ind_arg6[41+map2idx*105],arg14_l[41]);
    atomicAdd(&ind_arg6[42+map2idx*105],arg14_l[42]);
    atomicAdd(&ind_arg6[43+map2idx*105],arg14_l[43]);
    atomicAdd(&ind_arg6[44+map2idx*105],arg14_l[44]);
    atomicAdd(&ind_arg6[45+map2idx*105],arg14_l[45]);
    atomicAdd(&ind_arg6[46+map2idx*105],arg14_l[46]);
    atomicAdd(&ind_arg6[47+map2idx*105],arg14_l[47]);
    atomicAdd(&ind_arg6[48+map2idx*105],arg14_l[48]);
    atomicAdd(&ind_arg6[49+map2idx*105],arg14_l[49]);
    atomicAdd(&ind_arg6[50+map2idx*105],arg14_l[50]);
    atomicAdd(&ind_arg6[51+map2idx*105],arg14_l[51]);
    atomicAdd(&ind_arg6[52+map2idx*105],arg14_l[52]);
    atomicAdd(&ind_arg6[53+map2idx*105],arg14_l[53]);
    atomicAdd(&ind_arg6[54+map2idx*105],arg14_l[54]);
    atomicAdd(&ind_arg6[55+map2idx*105],arg14_l[55]);
    atomicAdd(&ind_arg6[56+map2idx*105],arg14_l[56]);
    atomicAdd(&ind_arg6[57+map2idx*105],arg14_l[57]);
    atomicAdd(&ind_arg6[58+map2idx*105],arg14_l[58]);
    atomicAdd(&ind_arg6[59+map2idx*105],arg14_l[59]);
    atomicAdd(&ind_arg6[60+map2idx*105],arg14_l[60]);
    atomicAdd(&ind_arg6[61+map2idx*105],arg14_l[61]);
    atomicAdd(&ind_arg6[62+map2idx*105],arg14_l[62]);
    atomicAdd(&ind_arg6[63+map2idx*105],arg14_l[63]);
    atomicAdd(&ind_arg6[64+map2idx*105],arg14_l[64]);
    atomicAdd(&ind_arg6[65+map2idx*105],arg14_l[65]);
    atomicAdd(&ind_arg6[66+map2idx*105],arg14_l[66]);
    atomicAdd(&ind_arg6[67+map2idx*105],arg14_l[67]);
    atomicAdd(&ind_arg6[68+map2idx*105],arg14_l[68]);
    atomicAdd(&ind_arg6[69+map2idx*105],arg14_l[69]);
    atomicAdd(&ind_arg6[70+map2idx*105],arg14_l[70]);
    atomicAdd(&ind_arg6[71+map2idx*105],arg14_l[71]);
    atomicAdd(&ind_arg6[72+map2idx*105],arg14_l[72]);
    atomicAdd(&ind_arg6[73+map2idx*105],arg14_l[73]);
    atomicAdd(&ind_arg6[74+map2idx*105],arg14_l[74]);
    atomicAdd(&ind_arg6[75+map2idx*105],arg14_l[75]);
    atomicAdd(&ind_arg6[76+map2idx*105],arg14_l[76]);
    atomicAdd(&ind_arg6[77+map2idx*105],arg14_l[77]);
    atomicAdd(&ind_arg6[78+map2idx*105],arg14_l[78]);
    atomicAdd(&ind_arg6[79+map2idx*105],arg14_l[79]);
    atomicAdd(&ind_arg6[80+map2idx*105],arg14_l[80]);
    atomicAdd(&ind_arg6[81+map2idx*105],arg14_l[81]);
    atomicAdd(&ind_arg6[82+map2idx*105],arg14_l[82]);
    atomicAdd(&ind_arg6[83+map2idx*105],arg14_l[83]);
    atomicAdd(&ind_arg6[84+map2idx*105],arg14_l[84]);
    atomicAdd(&ind_arg6[85+map2idx*105],arg14_l[85]);
    atomicAdd(&ind_arg6[86+map2idx*105],arg14_l[86]);
    atomicAdd(&ind_arg6[87+map2idx*105],arg14_l[87]);
    atomicAdd(&ind_arg6[88+map2idx*105],arg14_l[88]);
    atomicAdd(&ind_arg6[89+map2idx*105],arg14_l[89]);
    atomicAdd(&ind_arg6[90+map2idx*105],arg14_l[90]);
    atomicAdd(&ind_arg6[91+map2idx*105],arg14_l[91]);
    atomicAdd(&ind_arg6[92+map2idx*105],arg14_l[92]);
    atomicAdd(&ind_arg6[93+map2idx*105],arg14_l[93]);
    atomicAdd(&ind_arg6[94+map2idx*105],arg14_l[94]);
    atomicAdd(&ind_arg6[95+map2idx*105],arg14_l[95]);
    atomicAdd(&ind_arg6[96+map2idx*105],arg14_l[96]);
    atomicAdd(&ind_arg6[97+map2idx*105],arg14_l[97]);
    atomicAdd(&ind_arg6[98+map2idx*105],arg14_l[98]);
    atomicAdd(&ind_arg6[99+map2idx*105],arg14_l[99]);
    atomicAdd(&ind_arg6[100+map2idx*105],arg14_l[100]);
    atomicAdd(&ind_arg6[101+map2idx*105],arg14_l[101]);
    atomicAdd(&ind_arg6[102+map2idx*105],arg14_l[102]);
    atomicAdd(&ind_arg6[103+map2idx*105],arg14_l[103]);
    atomicAdd(&ind_arg6[104+map2idx*105],arg14_l[104]);
    atomicAdd(&ind_arg7[0+map1idx*105],arg15_l[0]);
    atomicAdd(&ind_arg7[1+map1idx*105],arg15_l[1]);
    atomicAdd(&ind_arg7[2+map1idx*105],arg15_l[2]);
    atomicAdd(&ind_arg7[3+map1idx*105],arg15_l[3]);
    atomicAdd(&ind_arg7[4+map1idx*105],arg15_l[4]);
    atomicAdd(&ind_arg7[5+map1idx*105],arg15_l[5]);
    atomicAdd(&ind_arg7[6+map1idx*105],arg15_l[6]);
    atomicAdd(&ind_arg7[7+map1idx*105],arg15_l[7]);
    atomicAdd(&ind_arg7[8+map1idx*105],arg15_l[8]);
    atomicAdd(&ind_arg7[9+map1idx*105],arg15_l[9]);
    atomicAdd(&ind_arg7[10+map1idx*105],arg15_l[10]);
    atomicAdd(&ind_arg7[11+map1idx*105],arg15_l[11]);
    atomicAdd(&ind_arg7[12+map1idx*105],arg15_l[12]);
    atomicAdd(&ind_arg7[13+map1idx*105],arg15_l[13]);
    atomicAdd(&ind_arg7[14+map1idx*105],arg15_l[14]);
    atomicAdd(&ind_arg7[15+map1idx*105],arg15_l[15]);
    atomicAdd(&ind_arg7[16+map1idx*105],arg15_l[16]);
    atomicAdd(&ind_arg7[17+map1idx*105],arg15_l[17]);
    atomicAdd(&ind_arg7[18+map1idx*105],arg15_l[18]);
    atomicAdd(&ind_arg7[19+map1idx*105],arg15_l[19]);
    atomicAdd(&ind_arg7[20+map1idx*105],arg15_l[20]);
    atomicAdd(&ind_arg7[21+map1idx*105],arg15_l[21]);
    atomicAdd(&ind_arg7[22+map1idx*105],arg15_l[22]);
    atomicAdd(&ind_arg7[23+map1idx*105],arg15_l[23]);
    atomicAdd(&ind_arg7[24+map1idx*105],arg15_l[24]);
    atomicAdd(&ind_arg7[25+map1idx*105],arg15_l[25]);
    atomicAdd(&ind_arg7[26+map1idx*105],arg15_l[26]);
    atomicAdd(&ind_arg7[27+map1idx*105],arg15_l[27]);
    atomicAdd(&ind_arg7[28+map1idx*105],arg15_l[28]);
    atomicAdd(&ind_arg7[29+map1idx*105],arg15_l[29]);
    atomicAdd(&ind_arg7[30+map1idx*105],arg15_l[30]);
    atomicAdd(&ind_arg7[31+map1idx*105],arg15_l[31]);
    atomicAdd(&ind_arg7[32+map1idx*105],arg15_l[32]);
    atomicAdd(&ind_arg7[33+map1idx*105],arg15_l[33]);
    atomicAdd(&ind_arg7[34+map1idx*105],arg15_l[34]);
    atomicAdd(&ind_arg7[35+map1idx*105],arg15_l[35]);
    atomicAdd(&ind_arg7[36+map1idx*105],arg15_l[36]);
    atomicAdd(&ind_arg7[37+map1idx*105],arg15_l[37]);
    atomicAdd(&ind_arg7[38+map1idx*105],arg15_l[38]);
    atomicAdd(&ind_arg7[39+map1idx*105],arg15_l[39]);
    atomicAdd(&ind_arg7[40+map1idx*105],arg15_l[40]);
    atomicAdd(&ind_arg7[41+map1idx*105],arg15_l[41]);
    atomicAdd(&ind_arg7[42+map1idx*105],arg15_l[42]);
    atomicAdd(&ind_arg7[43+map1idx*105],arg15_l[43]);
    atomicAdd(&ind_arg7[44+map1idx*105],arg15_l[44]);
    atomicAdd(&ind_arg7[45+map1idx*105],arg15_l[45]);
    atomicAdd(&ind_arg7[46+map1idx*105],arg15_l[46]);
    atomicAdd(&ind_arg7[47+map1idx*105],arg15_l[47]);
    atomicAdd(&ind_arg7[48+map1idx*105],arg15_l[48]);
    atomicAdd(&ind_arg7[49+map1idx*105],arg15_l[49]);
    atomicAdd(&ind_arg7[50+map1idx*105],arg15_l[50]);
    atomicAdd(&ind_arg7[51+map1idx*105],arg15_l[51]);
    atomicAdd(&ind_arg7[52+map1idx*105],arg15_l[52]);
    atomicAdd(&ind_arg7[53+map1idx*105],arg15_l[53]);
    atomicAdd(&ind_arg7[54+map1idx*105],arg15_l[54]);
    atomicAdd(&ind_arg7[55+map1idx*105],arg15_l[55]);
    atomicAdd(&ind_arg7[56+map1idx*105],arg15_l[56]);
    atomicAdd(&ind_arg7[57+map1idx*105],arg15_l[57]);
    atomicAdd(&ind_arg7[58+map1idx*105],arg15_l[58]);
    atomicAdd(&ind_arg7[59+map1idx*105],arg15_l[59]);
    atomicAdd(&ind_arg7[60+map1idx*105],arg15_l[60]);
    atomicAdd(&ind_arg7[61+map1idx*105],arg15_l[61]);
    atomicAdd(&ind_arg7[62+map1idx*105],arg15_l[62]);
    atomicAdd(&ind_arg7[63+map1idx*105],arg15_l[63]);
    atomicAdd(&ind_arg7[64+map1idx*105],arg15_l[64]);
    atomicAdd(&ind_arg7[65+map1idx*105],arg15_l[65]);
    atomicAdd(&ind_arg7[66+map1idx*105],arg15_l[66]);
    atomicAdd(&ind_arg7[67+map1idx*105],arg15_l[67]);
    atomicAdd(&ind_arg7[68+map1idx*105],arg15_l[68]);
    atomicAdd(&ind_arg7[69+map1idx*105],arg15_l[69]);
    atomicAdd(&ind_arg7[70+map1idx*105],arg15_l[70]);
    atomicAdd(&ind_arg7[71+map1idx*105],arg15_l[71]);
    atomicAdd(&ind_arg7[72+map1idx*105],arg15_l[72]);
    atomicAdd(&ind_arg7[73+map1idx*105],arg15_l[73]);
    atomicAdd(&ind_arg7[74+map1idx*105],arg15_l[74]);
    atomicAdd(&ind_arg7[75+map1idx*105],arg15_l[75]);
    atomicAdd(&ind_arg7[76+map1idx*105],arg15_l[76]);
    atomicAdd(&ind_arg7[77+map1idx*105],arg15_l[77]);
    atomicAdd(&ind_arg7[78+map1idx*105],arg15_l[78]);
    atomicAdd(&ind_arg7[79+map1idx*105],arg15_l[79]);
    atomicAdd(&ind_arg7[80+map1idx*105],arg15_l[80]);
    atomicAdd(&ind_arg7[81+map1idx*105],arg15_l[81]);
    atomicAdd(&ind_arg7[82+map1idx*105],arg15_l[82]);
    atomicAdd(&ind_arg7[83+map1idx*105],arg15_l[83]);
    atomicAdd(&ind_arg7[84+map1idx*105],arg15_l[84]);
    atomicAdd(&ind_arg7[85+map1idx*105],arg15_l[85]);
    atomicAdd(&ind_arg7[86+map1idx*105],arg15_l[86]);
    atomicAdd(&ind_arg7[87+map1idx*105],arg15_l[87]);
    atomicAdd(&ind_arg7[88+map1idx*105],arg15_l[88]);
    atomicAdd(&ind_arg7[89+map1idx*105],arg15_l[89]);
    atomicAdd(&ind_arg7[90+map1idx*105],arg15_l[90]);
    atomicAdd(&ind_arg7[91+map1idx*105],arg15_l[91]);
    atomicAdd(&ind_arg7[92+map1idx*105],arg15_l[92]);
    atomicAdd(&ind_arg7[93+map1idx*105],arg15_l[93]);
    atomicAdd(&ind_arg7[94+map1idx*105],arg15_l[94]);
    atomicAdd(&ind_arg7[95+map1idx*105],arg15_l[95]);
    atomicAdd(&ind_arg7[96+map1idx*105],arg15_l[96]);
    atomicAdd(&ind_arg7[97+map1idx*105],arg15_l[97]);
    atomicAdd(&ind_arg7[98+map1idx*105],arg15_l[98]);
    atomicAdd(&ind_arg7[99+map1idx*105],arg15_l[99]);
    atomicAdd(&ind_arg7[100+map1idx*105],arg15_l[100]);
    atomicAdd(&ind_arg7[101+map1idx*105],arg15_l[101]);
    atomicAdd(&ind_arg7[102+map1idx*105],arg15_l[102]);
    atomicAdd(&ind_arg7[103+map1idx*105],arg15_l[103]);
    atomicAdd(&ind_arg7[104+map1idx*105],arg15_l[104]);
    atomicAdd(&ind_arg7[0+map2idx*105],arg16_l[0]);
    atomicAdd(&ind_arg7[1+map2idx*105],arg16_l[1]);
    atomicAdd(&ind_arg7[2+map2idx*105],arg16_l[2]);
    atomicAdd(&ind_arg7[3+map2idx*105],arg16_l[3]);
    atomicAdd(&ind_arg7[4+map2idx*105],arg16_l[4]);
    atomicAdd(&ind_arg7[5+map2idx*105],arg16_l[5]);
    atomicAdd(&ind_arg7[6+map2idx*105],arg16_l[6]);
    atomicAdd(&ind_arg7[7+map2idx*105],arg16_l[7]);
    atomicAdd(&ind_arg7[8+map2idx*105],arg16_l[8]);
    atomicAdd(&ind_arg7[9+map2idx*105],arg16_l[9]);
    atomicAdd(&ind_arg7[10+map2idx*105],arg16_l[10]);
    atomicAdd(&ind_arg7[11+map2idx*105],arg16_l[11]);
    atomicAdd(&ind_arg7[12+map2idx*105],arg16_l[12]);
    atomicAdd(&ind_arg7[13+map2idx*105],arg16_l[13]);
    atomicAdd(&ind_arg7[14+map2idx*105],arg16_l[14]);
    atomicAdd(&ind_arg7[15+map2idx*105],arg16_l[15]);
    atomicAdd(&ind_arg7[16+map2idx*105],arg16_l[16]);
    atomicAdd(&ind_arg7[17+map2idx*105],arg16_l[17]);
    atomicAdd(&ind_arg7[18+map2idx*105],arg16_l[18]);
    atomicAdd(&ind_arg7[19+map2idx*105],arg16_l[19]);
    atomicAdd(&ind_arg7[20+map2idx*105],arg16_l[20]);
    atomicAdd(&ind_arg7[21+map2idx*105],arg16_l[21]);
    atomicAdd(&ind_arg7[22+map2idx*105],arg16_l[22]);
    atomicAdd(&ind_arg7[23+map2idx*105],arg16_l[23]);
    atomicAdd(&ind_arg7[24+map2idx*105],arg16_l[24]);
    atomicAdd(&ind_arg7[25+map2idx*105],arg16_l[25]);
    atomicAdd(&ind_arg7[26+map2idx*105],arg16_l[26]);
    atomicAdd(&ind_arg7[27+map2idx*105],arg16_l[27]);
    atomicAdd(&ind_arg7[28+map2idx*105],arg16_l[28]);
    atomicAdd(&ind_arg7[29+map2idx*105],arg16_l[29]);
    atomicAdd(&ind_arg7[30+map2idx*105],arg16_l[30]);
    atomicAdd(&ind_arg7[31+map2idx*105],arg16_l[31]);
    atomicAdd(&ind_arg7[32+map2idx*105],arg16_l[32]);
    atomicAdd(&ind_arg7[33+map2idx*105],arg16_l[33]);
    atomicAdd(&ind_arg7[34+map2idx*105],arg16_l[34]);
    atomicAdd(&ind_arg7[35+map2idx*105],arg16_l[35]);
    atomicAdd(&ind_arg7[36+map2idx*105],arg16_l[36]);
    atomicAdd(&ind_arg7[37+map2idx*105],arg16_l[37]);
    atomicAdd(&ind_arg7[38+map2idx*105],arg16_l[38]);
    atomicAdd(&ind_arg7[39+map2idx*105],arg16_l[39]);
    atomicAdd(&ind_arg7[40+map2idx*105],arg16_l[40]);
    atomicAdd(&ind_arg7[41+map2idx*105],arg16_l[41]);
    atomicAdd(&ind_arg7[42+map2idx*105],arg16_l[42]);
    atomicAdd(&ind_arg7[43+map2idx*105],arg16_l[43]);
    atomicAdd(&ind_arg7[44+map2idx*105],arg16_l[44]);
    atomicAdd(&ind_arg7[45+map2idx*105],arg16_l[45]);
    atomicAdd(&ind_arg7[46+map2idx*105],arg16_l[46]);
    atomicAdd(&ind_arg7[47+map2idx*105],arg16_l[47]);
    atomicAdd(&ind_arg7[48+map2idx*105],arg16_l[48]);
    atomicAdd(&ind_arg7[49+map2idx*105],arg16_l[49]);
    atomicAdd(&ind_arg7[50+map2idx*105],arg16_l[50]);
    atomicAdd(&ind_arg7[51+map2idx*105],arg16_l[51]);
    atomicAdd(&ind_arg7[52+map2idx*105],arg16_l[52]);
    atomicAdd(&ind_arg7[53+map2idx*105],arg16_l[53]);
    atomicAdd(&ind_arg7[54+map2idx*105],arg16_l[54]);
    atomicAdd(&ind_arg7[55+map2idx*105],arg16_l[55]);
    atomicAdd(&ind_arg7[56+map2idx*105],arg16_l[56]);
    atomicAdd(&ind_arg7[57+map2idx*105],arg16_l[57]);
    atomicAdd(&ind_arg7[58+map2idx*105],arg16_l[58]);
    atomicAdd(&ind_arg7[59+map2idx*105],arg16_l[59]);
    atomicAdd(&ind_arg7[60+map2idx*105],arg16_l[60]);
    atomicAdd(&ind_arg7[61+map2idx*105],arg16_l[61]);
    atomicAdd(&ind_arg7[62+map2idx*105],arg16_l[62]);
    atomicAdd(&ind_arg7[63+map2idx*105],arg16_l[63]);
    atomicAdd(&ind_arg7[64+map2idx*105],arg16_l[64]);
    atomicAdd(&ind_arg7[65+map2idx*105],arg16_l[65]);
    atomicAdd(&ind_arg7[66+map2idx*105],arg16_l[66]);
    atomicAdd(&ind_arg7[67+map2idx*105],arg16_l[67]);
    atomicAdd(&ind_arg7[68+map2idx*105],arg16_l[68]);
    atomicAdd(&ind_arg7[69+map2idx*105],arg16_l[69]);
    atomicAdd(&ind_arg7[70+map2idx*105],arg16_l[70]);
    atomicAdd(&ind_arg7[71+map2idx*105],arg16_l[71]);
    atomicAdd(&ind_arg7[72+map2idx*105],arg16_l[72]);
    atomicAdd(&ind_arg7[73+map2idx*105],arg16_l[73]);
    atomicAdd(&ind_arg7[74+map2idx*105],arg16_l[74]);
    atomicAdd(&ind_arg7[75+map2idx*105],arg16_l[75]);
    atomicAdd(&ind_arg7[76+map2idx*105],arg16_l[76]);
    atomicAdd(&ind_arg7[77+map2idx*105],arg16_l[77]);
    atomicAdd(&ind_arg7[78+map2idx*105],arg16_l[78]);
    atomicAdd(&ind_arg7[79+map2idx*105],arg16_l[79]);
    atomicAdd(&ind_arg7[80+map2idx*105],arg16_l[80]);
    atomicAdd(&ind_arg7[81+map2idx*105],arg16_l[81]);
    atomicAdd(&ind_arg7[82+map2idx*105],arg16_l[82]);
    atomicAdd(&ind_arg7[83+map2idx*105],arg16_l[83]);
    atomicAdd(&ind_arg7[84+map2idx*105],arg16_l[84]);
    atomicAdd(&ind_arg7[85+map2idx*105],arg16_l[85]);
    atomicAdd(&ind_arg7[86+map2idx*105],arg16_l[86]);
    atomicAdd(&ind_arg7[87+map2idx*105],arg16_l[87]);
    atomicAdd(&ind_arg7[88+map2idx*105],arg16_l[88]);
    atomicAdd(&ind_arg7[89+map2idx*105],arg16_l[89]);
    atomicAdd(&ind_arg7[90+map2idx*105],arg16_l[90]);
    atomicAdd(&ind_arg7[91+map2idx*105],arg16_l[91]);
    atomicAdd(&ind_arg7[92+map2idx*105],arg16_l[92]);
    atomicAdd(&ind_arg7[93+map2idx*105],arg16_l[93]);
    atomicAdd(&ind_arg7[94+map2idx*105],arg16_l[94]);
    atomicAdd(&ind_arg7[95+map2idx*105],arg16_l[95]);
    atomicAdd(&ind_arg7[96+map2idx*105],arg16_l[96]);
    atomicAdd(&ind_arg7[97+map2idx*105],arg16_l[97]);
    atomicAdd(&ind_arg7[98+map2idx*105],arg16_l[98]);
    atomicAdd(&ind_arg7[99+map2idx*105],arg16_l[99]);
    atomicAdd(&ind_arg7[100+map2idx*105],arg16_l[100]);
    atomicAdd(&ind_arg7[101+map2idx*105],arg16_l[101]);
    atomicAdd(&ind_arg7[102+map2idx*105],arg16_l[102]);
    atomicAdd(&ind_arg7[103+map2idx*105],arg16_l[103]);
    atomicAdd(&ind_arg7[104+map2idx*105],arg16_l[104]);
    atomicAdd(&ind_arg8[0+map1idx*105],arg17_l[0]);
    atomicAdd(&ind_arg8[1+map1idx*105],arg17_l[1]);
    atomicAdd(&ind_arg8[2+map1idx*105],arg17_l[2]);
    atomicAdd(&ind_arg8[3+map1idx*105],arg17_l[3]);
    atomicAdd(&ind_arg8[4+map1idx*105],arg17_l[4]);
    atomicAdd(&ind_arg8[5+map1idx*105],arg17_l[5]);
    atomicAdd(&ind_arg8[6+map1idx*105],arg17_l[6]);
    atomicAdd(&ind_arg8[7+map1idx*105],arg17_l[7]);
    atomicAdd(&ind_arg8[8+map1idx*105],arg17_l[8]);
    atomicAdd(&ind_arg8[9+map1idx*105],arg17_l[9]);
    atomicAdd(&ind_arg8[10+map1idx*105],arg17_l[10]);
    atomicAdd(&ind_arg8[11+map1idx*105],arg17_l[11]);
    atomicAdd(&ind_arg8[12+map1idx*105],arg17_l[12]);
    atomicAdd(&ind_arg8[13+map1idx*105],arg17_l[13]);
    atomicAdd(&ind_arg8[14+map1idx*105],arg17_l[14]);
    atomicAdd(&ind_arg8[15+map1idx*105],arg17_l[15]);
    atomicAdd(&ind_arg8[16+map1idx*105],arg17_l[16]);
    atomicAdd(&ind_arg8[17+map1idx*105],arg17_l[17]);
    atomicAdd(&ind_arg8[18+map1idx*105],arg17_l[18]);
    atomicAdd(&ind_arg8[19+map1idx*105],arg17_l[19]);
    atomicAdd(&ind_arg8[20+map1idx*105],arg17_l[20]);
    atomicAdd(&ind_arg8[21+map1idx*105],arg17_l[21]);
    atomicAdd(&ind_arg8[22+map1idx*105],arg17_l[22]);
    atomicAdd(&ind_arg8[23+map1idx*105],arg17_l[23]);
    atomicAdd(&ind_arg8[24+map1idx*105],arg17_l[24]);
    atomicAdd(&ind_arg8[25+map1idx*105],arg17_l[25]);
    atomicAdd(&ind_arg8[26+map1idx*105],arg17_l[26]);
    atomicAdd(&ind_arg8[27+map1idx*105],arg17_l[27]);
    atomicAdd(&ind_arg8[28+map1idx*105],arg17_l[28]);
    atomicAdd(&ind_arg8[29+map1idx*105],arg17_l[29]);
    atomicAdd(&ind_arg8[30+map1idx*105],arg17_l[30]);
    atomicAdd(&ind_arg8[31+map1idx*105],arg17_l[31]);
    atomicAdd(&ind_arg8[32+map1idx*105],arg17_l[32]);
    atomicAdd(&ind_arg8[33+map1idx*105],arg17_l[33]);
    atomicAdd(&ind_arg8[34+map1idx*105],arg17_l[34]);
    atomicAdd(&ind_arg8[35+map1idx*105],arg17_l[35]);
    atomicAdd(&ind_arg8[36+map1idx*105],arg17_l[36]);
    atomicAdd(&ind_arg8[37+map1idx*105],arg17_l[37]);
    atomicAdd(&ind_arg8[38+map1idx*105],arg17_l[38]);
    atomicAdd(&ind_arg8[39+map1idx*105],arg17_l[39]);
    atomicAdd(&ind_arg8[40+map1idx*105],arg17_l[40]);
    atomicAdd(&ind_arg8[41+map1idx*105],arg17_l[41]);
    atomicAdd(&ind_arg8[42+map1idx*105],arg17_l[42]);
    atomicAdd(&ind_arg8[43+map1idx*105],arg17_l[43]);
    atomicAdd(&ind_arg8[44+map1idx*105],arg17_l[44]);
    atomicAdd(&ind_arg8[45+map1idx*105],arg17_l[45]);
    atomicAdd(&ind_arg8[46+map1idx*105],arg17_l[46]);
    atomicAdd(&ind_arg8[47+map1idx*105],arg17_l[47]);
    atomicAdd(&ind_arg8[48+map1idx*105],arg17_l[48]);
    atomicAdd(&ind_arg8[49+map1idx*105],arg17_l[49]);
    atomicAdd(&ind_arg8[50+map1idx*105],arg17_l[50]);
    atomicAdd(&ind_arg8[51+map1idx*105],arg17_l[51]);
    atomicAdd(&ind_arg8[52+map1idx*105],arg17_l[52]);
    atomicAdd(&ind_arg8[53+map1idx*105],arg17_l[53]);
    atomicAdd(&ind_arg8[54+map1idx*105],arg17_l[54]);
    atomicAdd(&ind_arg8[55+map1idx*105],arg17_l[55]);
    atomicAdd(&ind_arg8[56+map1idx*105],arg17_l[56]);
    atomicAdd(&ind_arg8[57+map1idx*105],arg17_l[57]);
    atomicAdd(&ind_arg8[58+map1idx*105],arg17_l[58]);
    atomicAdd(&ind_arg8[59+map1idx*105],arg17_l[59]);
    atomicAdd(&ind_arg8[60+map1idx*105],arg17_l[60]);
    atomicAdd(&ind_arg8[61+map1idx*105],arg17_l[61]);
    atomicAdd(&ind_arg8[62+map1idx*105],arg17_l[62]);
    atomicAdd(&ind_arg8[63+map1idx*105],arg17_l[63]);
    atomicAdd(&ind_arg8[64+map1idx*105],arg17_l[64]);
    atomicAdd(&ind_arg8[65+map1idx*105],arg17_l[65]);
    atomicAdd(&ind_arg8[66+map1idx*105],arg17_l[66]);
    atomicAdd(&ind_arg8[67+map1idx*105],arg17_l[67]);
    atomicAdd(&ind_arg8[68+map1idx*105],arg17_l[68]);
    atomicAdd(&ind_arg8[69+map1idx*105],arg17_l[69]);
    atomicAdd(&ind_arg8[70+map1idx*105],arg17_l[70]);
    atomicAdd(&ind_arg8[71+map1idx*105],arg17_l[71]);
    atomicAdd(&ind_arg8[72+map1idx*105],arg17_l[72]);
    atomicAdd(&ind_arg8[73+map1idx*105],arg17_l[73]);
    atomicAdd(&ind_arg8[74+map1idx*105],arg17_l[74]);
    atomicAdd(&ind_arg8[75+map1idx*105],arg17_l[75]);
    atomicAdd(&ind_arg8[76+map1idx*105],arg17_l[76]);
    atomicAdd(&ind_arg8[77+map1idx*105],arg17_l[77]);
    atomicAdd(&ind_arg8[78+map1idx*105],arg17_l[78]);
    atomicAdd(&ind_arg8[79+map1idx*105],arg17_l[79]);
    atomicAdd(&ind_arg8[80+map1idx*105],arg17_l[80]);
    atomicAdd(&ind_arg8[81+map1idx*105],arg17_l[81]);
    atomicAdd(&ind_arg8[82+map1idx*105],arg17_l[82]);
    atomicAdd(&ind_arg8[83+map1idx*105],arg17_l[83]);
    atomicAdd(&ind_arg8[84+map1idx*105],arg17_l[84]);
    atomicAdd(&ind_arg8[85+map1idx*105],arg17_l[85]);
    atomicAdd(&ind_arg8[86+map1idx*105],arg17_l[86]);
    atomicAdd(&ind_arg8[87+map1idx*105],arg17_l[87]);
    atomicAdd(&ind_arg8[88+map1idx*105],arg17_l[88]);
    atomicAdd(&ind_arg8[89+map1idx*105],arg17_l[89]);
    atomicAdd(&ind_arg8[90+map1idx*105],arg17_l[90]);
    atomicAdd(&ind_arg8[91+map1idx*105],arg17_l[91]);
    atomicAdd(&ind_arg8[92+map1idx*105],arg17_l[92]);
    atomicAdd(&ind_arg8[93+map1idx*105],arg17_l[93]);
    atomicAdd(&ind_arg8[94+map1idx*105],arg17_l[94]);
    atomicAdd(&ind_arg8[95+map1idx*105],arg17_l[95]);
    atomicAdd(&ind_arg8[96+map1idx*105],arg17_l[96]);
    atomicAdd(&ind_arg8[97+map1idx*105],arg17_l[97]);
    atomicAdd(&ind_arg8[98+map1idx*105],arg17_l[98]);
    atomicAdd(&ind_arg8[99+map1idx*105],arg17_l[99]);
    atomicAdd(&ind_arg8[100+map1idx*105],arg17_l[100]);
    atomicAdd(&ind_arg8[101+map1idx*105],arg17_l[101]);
    atomicAdd(&ind_arg8[102+map1idx*105],arg17_l[102]);
    atomicAdd(&ind_arg8[103+map1idx*105],arg17_l[103]);
    atomicAdd(&ind_arg8[104+map1idx*105],arg17_l[104]);
    atomicAdd(&ind_arg8[0+map2idx*105],arg18_l[0]);
    atomicAdd(&ind_arg8[1+map2idx*105],arg18_l[1]);
    atomicAdd(&ind_arg8[2+map2idx*105],arg18_l[2]);
    atomicAdd(&ind_arg8[3+map2idx*105],arg18_l[3]);
    atomicAdd(&ind_arg8[4+map2idx*105],arg18_l[4]);
    atomicAdd(&ind_arg8[5+map2idx*105],arg18_l[5]);
    atomicAdd(&ind_arg8[6+map2idx*105],arg18_l[6]);
    atomicAdd(&ind_arg8[7+map2idx*105],arg18_l[7]);
    atomicAdd(&ind_arg8[8+map2idx*105],arg18_l[8]);
    atomicAdd(&ind_arg8[9+map2idx*105],arg18_l[9]);
    atomicAdd(&ind_arg8[10+map2idx*105],arg18_l[10]);
    atomicAdd(&ind_arg8[11+map2idx*105],arg18_l[11]);
    atomicAdd(&ind_arg8[12+map2idx*105],arg18_l[12]);
    atomicAdd(&ind_arg8[13+map2idx*105],arg18_l[13]);
    atomicAdd(&ind_arg8[14+map2idx*105],arg18_l[14]);
    atomicAdd(&ind_arg8[15+map2idx*105],arg18_l[15]);
    atomicAdd(&ind_arg8[16+map2idx*105],arg18_l[16]);
    atomicAdd(&ind_arg8[17+map2idx*105],arg18_l[17]);
    atomicAdd(&ind_arg8[18+map2idx*105],arg18_l[18]);
    atomicAdd(&ind_arg8[19+map2idx*105],arg18_l[19]);
    atomicAdd(&ind_arg8[20+map2idx*105],arg18_l[20]);
    atomicAdd(&ind_arg8[21+map2idx*105],arg18_l[21]);
    atomicAdd(&ind_arg8[22+map2idx*105],arg18_l[22]);
    atomicAdd(&ind_arg8[23+map2idx*105],arg18_l[23]);
    atomicAdd(&ind_arg8[24+map2idx*105],arg18_l[24]);
    atomicAdd(&ind_arg8[25+map2idx*105],arg18_l[25]);
    atomicAdd(&ind_arg8[26+map2idx*105],arg18_l[26]);
    atomicAdd(&ind_arg8[27+map2idx*105],arg18_l[27]);
    atomicAdd(&ind_arg8[28+map2idx*105],arg18_l[28]);
    atomicAdd(&ind_arg8[29+map2idx*105],arg18_l[29]);
    atomicAdd(&ind_arg8[30+map2idx*105],arg18_l[30]);
    atomicAdd(&ind_arg8[31+map2idx*105],arg18_l[31]);
    atomicAdd(&ind_arg8[32+map2idx*105],arg18_l[32]);
    atomicAdd(&ind_arg8[33+map2idx*105],arg18_l[33]);
    atomicAdd(&ind_arg8[34+map2idx*105],arg18_l[34]);
    atomicAdd(&ind_arg8[35+map2idx*105],arg18_l[35]);
    atomicAdd(&ind_arg8[36+map2idx*105],arg18_l[36]);
    atomicAdd(&ind_arg8[37+map2idx*105],arg18_l[37]);
    atomicAdd(&ind_arg8[38+map2idx*105],arg18_l[38]);
    atomicAdd(&ind_arg8[39+map2idx*105],arg18_l[39]);
    atomicAdd(&ind_arg8[40+map2idx*105],arg18_l[40]);
    atomicAdd(&ind_arg8[41+map2idx*105],arg18_l[41]);
    atomicAdd(&ind_arg8[42+map2idx*105],arg18_l[42]);
    atomicAdd(&ind_arg8[43+map2idx*105],arg18_l[43]);
    atomicAdd(&ind_arg8[44+map2idx*105],arg18_l[44]);
    atomicAdd(&ind_arg8[45+map2idx*105],arg18_l[45]);
    atomicAdd(&ind_arg8[46+map2idx*105],arg18_l[46]);
    atomicAdd(&ind_arg8[47+map2idx*105],arg18_l[47]);
    atomicAdd(&ind_arg8[48+map2idx*105],arg18_l[48]);
    atomicAdd(&ind_arg8[49+map2idx*105],arg18_l[49]);
    atomicAdd(&ind_arg8[50+map2idx*105],arg18_l[50]);
    atomicAdd(&ind_arg8[51+map2idx*105],arg18_l[51]);
    atomicAdd(&ind_arg8[52+map2idx*105],arg18_l[52]);
    atomicAdd(&ind_arg8[53+map2idx*105],arg18_l[53]);
    atomicAdd(&ind_arg8[54+map2idx*105],arg18_l[54]);
    atomicAdd(&ind_arg8[55+map2idx*105],arg18_l[55]);
    atomicAdd(&ind_arg8[56+map2idx*105],arg18_l[56]);
    atomicAdd(&ind_arg8[57+map2idx*105],arg18_l[57]);
    atomicAdd(&ind_arg8[58+map2idx*105],arg18_l[58]);
    atomicAdd(&ind_arg8[59+map2idx*105],arg18_l[59]);
    atomicAdd(&ind_arg8[60+map2idx*105],arg18_l[60]);
    atomicAdd(&ind_arg8[61+map2idx*105],arg18_l[61]);
    atomicAdd(&ind_arg8[62+map2idx*105],arg18_l[62]);
    atomicAdd(&ind_arg8[63+map2idx*105],arg18_l[63]);
    atomicAdd(&ind_arg8[64+map2idx*105],arg18_l[64]);
    atomicAdd(&ind_arg8[65+map2idx*105],arg18_l[65]);
    atomicAdd(&ind_arg8[66+map2idx*105],arg18_l[66]);
    atomicAdd(&ind_arg8[67+map2idx*105],arg18_l[67]);
    atomicAdd(&ind_arg8[68+map2idx*105],arg18_l[68]);
    atomicAdd(&ind_arg8[69+map2idx*105],arg18_l[69]);
    atomicAdd(&ind_arg8[70+map2idx*105],arg18_l[70]);
    atomicAdd(&ind_arg8[71+map2idx*105],arg18_l[71]);
    atomicAdd(&ind_arg8[72+map2idx*105],arg18_l[72]);
    atomicAdd(&ind_arg8[73+map2idx*105],arg18_l[73]);
    atomicAdd(&ind_arg8[74+map2idx*105],arg18_l[74]);
    atomicAdd(&ind_arg8[75+map2idx*105],arg18_l[75]);
    atomicAdd(&ind_arg8[76+map2idx*105],arg18_l[76]);
    atomicAdd(&ind_arg8[77+map2idx*105],arg18_l[77]);
    atomicAdd(&ind_arg8[78+map2idx*105],arg18_l[78]);
    atomicAdd(&ind_arg8[79+map2idx*105],arg18_l[79]);
    atomicAdd(&ind_arg8[80+map2idx*105],arg18_l[80]);
    atomicAdd(&ind_arg8[81+map2idx*105],arg18_l[81]);
    atomicAdd(&ind_arg8[82+map2idx*105],arg18_l[82]);
    atomicAdd(&ind_arg8[83+map2idx*105],arg18_l[83]);
    atomicAdd(&ind_arg8[84+map2idx*105],arg18_l[84]);
    atomicAdd(&ind_arg8[85+map2idx*105],arg18_l[85]);
    atomicAdd(&ind_arg8[86+map2idx*105],arg18_l[86]);
    atomicAdd(&ind_arg8[87+map2idx*105],arg18_l[87]);
    atomicAdd(&ind_arg8[88+map2idx*105],arg18_l[88]);
    atomicAdd(&ind_arg8[89+map2idx*105],arg18_l[89]);
    atomicAdd(&ind_arg8[90+map2idx*105],arg18_l[90]);
    atomicAdd(&ind_arg8[91+map2idx*105],arg18_l[91]);
    atomicAdd(&ind_arg8[92+map2idx*105],arg18_l[92]);
    atomicAdd(&ind_arg8[93+map2idx*105],arg18_l[93]);
    atomicAdd(&ind_arg8[94+map2idx*105],arg18_l[94]);
    atomicAdd(&ind_arg8[95+map2idx*105],arg18_l[95]);
    atomicAdd(&ind_arg8[96+map2idx*105],arg18_l[96]);
    atomicAdd(&ind_arg8[97+map2idx*105],arg18_l[97]);
    atomicAdd(&ind_arg8[98+map2idx*105],arg18_l[98]);
    atomicAdd(&ind_arg8[99+map2idx*105],arg18_l[99]);
    atomicAdd(&ind_arg8[100+map2idx*105],arg18_l[100]);
    atomicAdd(&ind_arg8[101+map2idx*105],arg18_l[101]);
    atomicAdd(&ind_arg8[102+map2idx*105],arg18_l[102]);
    atomicAdd(&ind_arg8[103+map2idx*105],arg18_l[103]);
    atomicAdd(&ind_arg8[104+map2idx*105],arg18_l[104]);
    atomicAdd(&ind_arg9[0+map1idx*105],arg19_l[0]);
    atomicAdd(&ind_arg9[1+map1idx*105],arg19_l[1]);
    atomicAdd(&ind_arg9[2+map1idx*105],arg19_l[2]);
    atomicAdd(&ind_arg9[3+map1idx*105],arg19_l[3]);
    atomicAdd(&ind_arg9[4+map1idx*105],arg19_l[4]);
    atomicAdd(&ind_arg9[5+map1idx*105],arg19_l[5]);
    atomicAdd(&ind_arg9[6+map1idx*105],arg19_l[6]);
    atomicAdd(&ind_arg9[7+map1idx*105],arg19_l[7]);
    atomicAdd(&ind_arg9[8+map1idx*105],arg19_l[8]);
    atomicAdd(&ind_arg9[9+map1idx*105],arg19_l[9]);
    atomicAdd(&ind_arg9[10+map1idx*105],arg19_l[10]);
    atomicAdd(&ind_arg9[11+map1idx*105],arg19_l[11]);
    atomicAdd(&ind_arg9[12+map1idx*105],arg19_l[12]);
    atomicAdd(&ind_arg9[13+map1idx*105],arg19_l[13]);
    atomicAdd(&ind_arg9[14+map1idx*105],arg19_l[14]);
    atomicAdd(&ind_arg9[15+map1idx*105],arg19_l[15]);
    atomicAdd(&ind_arg9[16+map1idx*105],arg19_l[16]);
    atomicAdd(&ind_arg9[17+map1idx*105],arg19_l[17]);
    atomicAdd(&ind_arg9[18+map1idx*105],arg19_l[18]);
    atomicAdd(&ind_arg9[19+map1idx*105],arg19_l[19]);
    atomicAdd(&ind_arg9[20+map1idx*105],arg19_l[20]);
    atomicAdd(&ind_arg9[21+map1idx*105],arg19_l[21]);
    atomicAdd(&ind_arg9[22+map1idx*105],arg19_l[22]);
    atomicAdd(&ind_arg9[23+map1idx*105],arg19_l[23]);
    atomicAdd(&ind_arg9[24+map1idx*105],arg19_l[24]);
    atomicAdd(&ind_arg9[25+map1idx*105],arg19_l[25]);
    atomicAdd(&ind_arg9[26+map1idx*105],arg19_l[26]);
    atomicAdd(&ind_arg9[27+map1idx*105],arg19_l[27]);
    atomicAdd(&ind_arg9[28+map1idx*105],arg19_l[28]);
    atomicAdd(&ind_arg9[29+map1idx*105],arg19_l[29]);
    atomicAdd(&ind_arg9[30+map1idx*105],arg19_l[30]);
    atomicAdd(&ind_arg9[31+map1idx*105],arg19_l[31]);
    atomicAdd(&ind_arg9[32+map1idx*105],arg19_l[32]);
    atomicAdd(&ind_arg9[33+map1idx*105],arg19_l[33]);
    atomicAdd(&ind_arg9[34+map1idx*105],arg19_l[34]);
    atomicAdd(&ind_arg9[35+map1idx*105],arg19_l[35]);
    atomicAdd(&ind_arg9[36+map1idx*105],arg19_l[36]);
    atomicAdd(&ind_arg9[37+map1idx*105],arg19_l[37]);
    atomicAdd(&ind_arg9[38+map1idx*105],arg19_l[38]);
    atomicAdd(&ind_arg9[39+map1idx*105],arg19_l[39]);
    atomicAdd(&ind_arg9[40+map1idx*105],arg19_l[40]);
    atomicAdd(&ind_arg9[41+map1idx*105],arg19_l[41]);
    atomicAdd(&ind_arg9[42+map1idx*105],arg19_l[42]);
    atomicAdd(&ind_arg9[43+map1idx*105],arg19_l[43]);
    atomicAdd(&ind_arg9[44+map1idx*105],arg19_l[44]);
    atomicAdd(&ind_arg9[45+map1idx*105],arg19_l[45]);
    atomicAdd(&ind_arg9[46+map1idx*105],arg19_l[46]);
    atomicAdd(&ind_arg9[47+map1idx*105],arg19_l[47]);
    atomicAdd(&ind_arg9[48+map1idx*105],arg19_l[48]);
    atomicAdd(&ind_arg9[49+map1idx*105],arg19_l[49]);
    atomicAdd(&ind_arg9[50+map1idx*105],arg19_l[50]);
    atomicAdd(&ind_arg9[51+map1idx*105],arg19_l[51]);
    atomicAdd(&ind_arg9[52+map1idx*105],arg19_l[52]);
    atomicAdd(&ind_arg9[53+map1idx*105],arg19_l[53]);
    atomicAdd(&ind_arg9[54+map1idx*105],arg19_l[54]);
    atomicAdd(&ind_arg9[55+map1idx*105],arg19_l[55]);
    atomicAdd(&ind_arg9[56+map1idx*105],arg19_l[56]);
    atomicAdd(&ind_arg9[57+map1idx*105],arg19_l[57]);
    atomicAdd(&ind_arg9[58+map1idx*105],arg19_l[58]);
    atomicAdd(&ind_arg9[59+map1idx*105],arg19_l[59]);
    atomicAdd(&ind_arg9[60+map1idx*105],arg19_l[60]);
    atomicAdd(&ind_arg9[61+map1idx*105],arg19_l[61]);
    atomicAdd(&ind_arg9[62+map1idx*105],arg19_l[62]);
    atomicAdd(&ind_arg9[63+map1idx*105],arg19_l[63]);
    atomicAdd(&ind_arg9[64+map1idx*105],arg19_l[64]);
    atomicAdd(&ind_arg9[65+map1idx*105],arg19_l[65]);
    atomicAdd(&ind_arg9[66+map1idx*105],arg19_l[66]);
    atomicAdd(&ind_arg9[67+map1idx*105],arg19_l[67]);
    atomicAdd(&ind_arg9[68+map1idx*105],arg19_l[68]);
    atomicAdd(&ind_arg9[69+map1idx*105],arg19_l[69]);
    atomicAdd(&ind_arg9[70+map1idx*105],arg19_l[70]);
    atomicAdd(&ind_arg9[71+map1idx*105],arg19_l[71]);
    atomicAdd(&ind_arg9[72+map1idx*105],arg19_l[72]);
    atomicAdd(&ind_arg9[73+map1idx*105],arg19_l[73]);
    atomicAdd(&ind_arg9[74+map1idx*105],arg19_l[74]);
    atomicAdd(&ind_arg9[75+map1idx*105],arg19_l[75]);
    atomicAdd(&ind_arg9[76+map1idx*105],arg19_l[76]);
    atomicAdd(&ind_arg9[77+map1idx*105],arg19_l[77]);
    atomicAdd(&ind_arg9[78+map1idx*105],arg19_l[78]);
    atomicAdd(&ind_arg9[79+map1idx*105],arg19_l[79]);
    atomicAdd(&ind_arg9[80+map1idx*105],arg19_l[80]);
    atomicAdd(&ind_arg9[81+map1idx*105],arg19_l[81]);
    atomicAdd(&ind_arg9[82+map1idx*105],arg19_l[82]);
    atomicAdd(&ind_arg9[83+map1idx*105],arg19_l[83]);
    atomicAdd(&ind_arg9[84+map1idx*105],arg19_l[84]);
    atomicAdd(&ind_arg9[85+map1idx*105],arg19_l[85]);
    atomicAdd(&ind_arg9[86+map1idx*105],arg19_l[86]);
    atomicAdd(&ind_arg9[87+map1idx*105],arg19_l[87]);
    atomicAdd(&ind_arg9[88+map1idx*105],arg19_l[88]);
    atomicAdd(&ind_arg9[89+map1idx*105],arg19_l[89]);
    atomicAdd(&ind_arg9[90+map1idx*105],arg19_l[90]);
    atomicAdd(&ind_arg9[91+map1idx*105],arg19_l[91]);
    atomicAdd(&ind_arg9[92+map1idx*105],arg19_l[92]);
    atomicAdd(&ind_arg9[93+map1idx*105],arg19_l[93]);
    atomicAdd(&ind_arg9[94+map1idx*105],arg19_l[94]);
    atomicAdd(&ind_arg9[95+map1idx*105],arg19_l[95]);
    atomicAdd(&ind_arg9[96+map1idx*105],arg19_l[96]);
    atomicAdd(&ind_arg9[97+map1idx*105],arg19_l[97]);
    atomicAdd(&ind_arg9[98+map1idx*105],arg19_l[98]);
    atomicAdd(&ind_arg9[99+map1idx*105],arg19_l[99]);
    atomicAdd(&ind_arg9[100+map1idx*105],arg19_l[100]);
    atomicAdd(&ind_arg9[101+map1idx*105],arg19_l[101]);
    atomicAdd(&ind_arg9[102+map1idx*105],arg19_l[102]);
    atomicAdd(&ind_arg9[103+map1idx*105],arg19_l[103]);
    atomicAdd(&ind_arg9[104+map1idx*105],arg19_l[104]);
    atomicAdd(&ind_arg9[0+map2idx*105],arg20_l[0]);
    atomicAdd(&ind_arg9[1+map2idx*105],arg20_l[1]);
    atomicAdd(&ind_arg9[2+map2idx*105],arg20_l[2]);
    atomicAdd(&ind_arg9[3+map2idx*105],arg20_l[3]);
    atomicAdd(&ind_arg9[4+map2idx*105],arg20_l[4]);
    atomicAdd(&ind_arg9[5+map2idx*105],arg20_l[5]);
    atomicAdd(&ind_arg9[6+map2idx*105],arg20_l[6]);
    atomicAdd(&ind_arg9[7+map2idx*105],arg20_l[7]);
    atomicAdd(&ind_arg9[8+map2idx*105],arg20_l[8]);
    atomicAdd(&ind_arg9[9+map2idx*105],arg20_l[9]);
    atomicAdd(&ind_arg9[10+map2idx*105],arg20_l[10]);
    atomicAdd(&ind_arg9[11+map2idx*105],arg20_l[11]);
    atomicAdd(&ind_arg9[12+map2idx*105],arg20_l[12]);
    atomicAdd(&ind_arg9[13+map2idx*105],arg20_l[13]);
    atomicAdd(&ind_arg9[14+map2idx*105],arg20_l[14]);
    atomicAdd(&ind_arg9[15+map2idx*105],arg20_l[15]);
    atomicAdd(&ind_arg9[16+map2idx*105],arg20_l[16]);
    atomicAdd(&ind_arg9[17+map2idx*105],arg20_l[17]);
    atomicAdd(&ind_arg9[18+map2idx*105],arg20_l[18]);
    atomicAdd(&ind_arg9[19+map2idx*105],arg20_l[19]);
    atomicAdd(&ind_arg9[20+map2idx*105],arg20_l[20]);
    atomicAdd(&ind_arg9[21+map2idx*105],arg20_l[21]);
    atomicAdd(&ind_arg9[22+map2idx*105],arg20_l[22]);
    atomicAdd(&ind_arg9[23+map2idx*105],arg20_l[23]);
    atomicAdd(&ind_arg9[24+map2idx*105],arg20_l[24]);
    atomicAdd(&ind_arg9[25+map2idx*105],arg20_l[25]);
    atomicAdd(&ind_arg9[26+map2idx*105],arg20_l[26]);
    atomicAdd(&ind_arg9[27+map2idx*105],arg20_l[27]);
    atomicAdd(&ind_arg9[28+map2idx*105],arg20_l[28]);
    atomicAdd(&ind_arg9[29+map2idx*105],arg20_l[29]);
    atomicAdd(&ind_arg9[30+map2idx*105],arg20_l[30]);
    atomicAdd(&ind_arg9[31+map2idx*105],arg20_l[31]);
    atomicAdd(&ind_arg9[32+map2idx*105],arg20_l[32]);
    atomicAdd(&ind_arg9[33+map2idx*105],arg20_l[33]);
    atomicAdd(&ind_arg9[34+map2idx*105],arg20_l[34]);
    atomicAdd(&ind_arg9[35+map2idx*105],arg20_l[35]);
    atomicAdd(&ind_arg9[36+map2idx*105],arg20_l[36]);
    atomicAdd(&ind_arg9[37+map2idx*105],arg20_l[37]);
    atomicAdd(&ind_arg9[38+map2idx*105],arg20_l[38]);
    atomicAdd(&ind_arg9[39+map2idx*105],arg20_l[39]);
    atomicAdd(&ind_arg9[40+map2idx*105],arg20_l[40]);
    atomicAdd(&ind_arg9[41+map2idx*105],arg20_l[41]);
    atomicAdd(&ind_arg9[42+map2idx*105],arg20_l[42]);
    atomicAdd(&ind_arg9[43+map2idx*105],arg20_l[43]);
    atomicAdd(&ind_arg9[44+map2idx*105],arg20_l[44]);
    atomicAdd(&ind_arg9[45+map2idx*105],arg20_l[45]);
    atomicAdd(&ind_arg9[46+map2idx*105],arg20_l[46]);
    atomicAdd(&ind_arg9[47+map2idx*105],arg20_l[47]);
    atomicAdd(&ind_arg9[48+map2idx*105],arg20_l[48]);
    atomicAdd(&ind_arg9[49+map2idx*105],arg20_l[49]);
    atomicAdd(&ind_arg9[50+map2idx*105],arg20_l[50]);
    atomicAdd(&ind_arg9[51+map2idx*105],arg20_l[51]);
    atomicAdd(&ind_arg9[52+map2idx*105],arg20_l[52]);
    atomicAdd(&ind_arg9[53+map2idx*105],arg20_l[53]);
    atomicAdd(&ind_arg9[54+map2idx*105],arg20_l[54]);
    atomicAdd(&ind_arg9[55+map2idx*105],arg20_l[55]);
    atomicAdd(&ind_arg9[56+map2idx*105],arg20_l[56]);
    atomicAdd(&ind_arg9[57+map2idx*105],arg20_l[57]);
    atomicAdd(&ind_arg9[58+map2idx*105],arg20_l[58]);
    atomicAdd(&ind_arg9[59+map2idx*105],arg20_l[59]);
    atomicAdd(&ind_arg9[60+map2idx*105],arg20_l[60]);
    atomicAdd(&ind_arg9[61+map2idx*105],arg20_l[61]);
    atomicAdd(&ind_arg9[62+map2idx*105],arg20_l[62]);
    atomicAdd(&ind_arg9[63+map2idx*105],arg20_l[63]);
    atomicAdd(&ind_arg9[64+map2idx*105],arg20_l[64]);
    atomicAdd(&ind_arg9[65+map2idx*105],arg20_l[65]);
    atomicAdd(&ind_arg9[66+map2idx*105],arg20_l[66]);
    atomicAdd(&ind_arg9[67+map2idx*105],arg20_l[67]);
    atomicAdd(&ind_arg9[68+map2idx*105],arg20_l[68]);
    atomicAdd(&ind_arg9[69+map2idx*105],arg20_l[69]);
    atomicAdd(&ind_arg9[70+map2idx*105],arg20_l[70]);
    atomicAdd(&ind_arg9[71+map2idx*105],arg20_l[71]);
    atomicAdd(&ind_arg9[72+map2idx*105],arg20_l[72]);
    atomicAdd(&ind_arg9[73+map2idx*105],arg20_l[73]);
    atomicAdd(&ind_arg9[74+map2idx*105],arg20_l[74]);
    atomicAdd(&ind_arg9[75+map2idx*105],arg20_l[75]);
    atomicAdd(&ind_arg9[76+map2idx*105],arg20_l[76]);
    atomicAdd(&ind_arg9[77+map2idx*105],arg20_l[77]);
    atomicAdd(&ind_arg9[78+map2idx*105],arg20_l[78]);
    atomicAdd(&ind_arg9[79+map2idx*105],arg20_l[79]);
    atomicAdd(&ind_arg9[80+map2idx*105],arg20_l[80]);
    atomicAdd(&ind_arg9[81+map2idx*105],arg20_l[81]);
    atomicAdd(&ind_arg9[82+map2idx*105],arg20_l[82]);
    atomicAdd(&ind_arg9[83+map2idx*105],arg20_l[83]);
    atomicAdd(&ind_arg9[84+map2idx*105],arg20_l[84]);
    atomicAdd(&ind_arg9[85+map2idx*105],arg20_l[85]);
    atomicAdd(&ind_arg9[86+map2idx*105],arg20_l[86]);
    atomicAdd(&ind_arg9[87+map2idx*105],arg20_l[87]);
    atomicAdd(&ind_arg9[88+map2idx*105],arg20_l[88]);
    atomicAdd(&ind_arg9[89+map2idx*105],arg20_l[89]);
    atomicAdd(&ind_arg9[90+map2idx*105],arg20_l[90]);
    atomicAdd(&ind_arg9[91+map2idx*105],arg20_l[91]);
    atomicAdd(&ind_arg9[92+map2idx*105],arg20_l[92]);
    atomicAdd(&ind_arg9[93+map2idx*105],arg20_l[93]);
    atomicAdd(&ind_arg9[94+map2idx*105],arg20_l[94]);
    atomicAdd(&ind_arg9[95+map2idx*105],arg20_l[95]);
    atomicAdd(&ind_arg9[96+map2idx*105],arg20_l[96]);
    atomicAdd(&ind_arg9[97+map2idx*105],arg20_l[97]);
    atomicAdd(&ind_arg9[98+map2idx*105],arg20_l[98]);
    atomicAdd(&ind_arg9[99+map2idx*105],arg20_l[99]);
    atomicAdd(&ind_arg9[100+map2idx*105],arg20_l[100]);
    atomicAdd(&ind_arg9[101+map2idx*105],arg20_l[101]);
    atomicAdd(&ind_arg9[102+map2idx*105],arg20_l[102]);
    atomicAdd(&ind_arg9[103+map2idx*105],arg20_l[103]);
    atomicAdd(&ind_arg9[104+map2idx*105],arg20_l[104]);
    atomicAdd(&ind_arg10[0+map1idx*105],arg21_l[0]);
    atomicAdd(&ind_arg10[1+map1idx*105],arg21_l[1]);
    atomicAdd(&ind_arg10[2+map1idx*105],arg21_l[2]);
    atomicAdd(&ind_arg10[3+map1idx*105],arg21_l[3]);
    atomicAdd(&ind_arg10[4+map1idx*105],arg21_l[4]);
    atomicAdd(&ind_arg10[5+map1idx*105],arg21_l[5]);
    atomicAdd(&ind_arg10[6+map1idx*105],arg21_l[6]);
    atomicAdd(&ind_arg10[7+map1idx*105],arg21_l[7]);
    atomicAdd(&ind_arg10[8+map1idx*105],arg21_l[8]);
    atomicAdd(&ind_arg10[9+map1idx*105],arg21_l[9]);
    atomicAdd(&ind_arg10[10+map1idx*105],arg21_l[10]);
    atomicAdd(&ind_arg10[11+map1idx*105],arg21_l[11]);
    atomicAdd(&ind_arg10[12+map1idx*105],arg21_l[12]);
    atomicAdd(&ind_arg10[13+map1idx*105],arg21_l[13]);
    atomicAdd(&ind_arg10[14+map1idx*105],arg21_l[14]);
    atomicAdd(&ind_arg10[15+map1idx*105],arg21_l[15]);
    atomicAdd(&ind_arg10[16+map1idx*105],arg21_l[16]);
    atomicAdd(&ind_arg10[17+map1idx*105],arg21_l[17]);
    atomicAdd(&ind_arg10[18+map1idx*105],arg21_l[18]);
    atomicAdd(&ind_arg10[19+map1idx*105],arg21_l[19]);
    atomicAdd(&ind_arg10[20+map1idx*105],arg21_l[20]);
    atomicAdd(&ind_arg10[21+map1idx*105],arg21_l[21]);
    atomicAdd(&ind_arg10[22+map1idx*105],arg21_l[22]);
    atomicAdd(&ind_arg10[23+map1idx*105],arg21_l[23]);
    atomicAdd(&ind_arg10[24+map1idx*105],arg21_l[24]);
    atomicAdd(&ind_arg10[25+map1idx*105],arg21_l[25]);
    atomicAdd(&ind_arg10[26+map1idx*105],arg21_l[26]);
    atomicAdd(&ind_arg10[27+map1idx*105],arg21_l[27]);
    atomicAdd(&ind_arg10[28+map1idx*105],arg21_l[28]);
    atomicAdd(&ind_arg10[29+map1idx*105],arg21_l[29]);
    atomicAdd(&ind_arg10[30+map1idx*105],arg21_l[30]);
    atomicAdd(&ind_arg10[31+map1idx*105],arg21_l[31]);
    atomicAdd(&ind_arg10[32+map1idx*105],arg21_l[32]);
    atomicAdd(&ind_arg10[33+map1idx*105],arg21_l[33]);
    atomicAdd(&ind_arg10[34+map1idx*105],arg21_l[34]);
    atomicAdd(&ind_arg10[35+map1idx*105],arg21_l[35]);
    atomicAdd(&ind_arg10[36+map1idx*105],arg21_l[36]);
    atomicAdd(&ind_arg10[37+map1idx*105],arg21_l[37]);
    atomicAdd(&ind_arg10[38+map1idx*105],arg21_l[38]);
    atomicAdd(&ind_arg10[39+map1idx*105],arg21_l[39]);
    atomicAdd(&ind_arg10[40+map1idx*105],arg21_l[40]);
    atomicAdd(&ind_arg10[41+map1idx*105],arg21_l[41]);
    atomicAdd(&ind_arg10[42+map1idx*105],arg21_l[42]);
    atomicAdd(&ind_arg10[43+map1idx*105],arg21_l[43]);
    atomicAdd(&ind_arg10[44+map1idx*105],arg21_l[44]);
    atomicAdd(&ind_arg10[45+map1idx*105],arg21_l[45]);
    atomicAdd(&ind_arg10[46+map1idx*105],arg21_l[46]);
    atomicAdd(&ind_arg10[47+map1idx*105],arg21_l[47]);
    atomicAdd(&ind_arg10[48+map1idx*105],arg21_l[48]);
    atomicAdd(&ind_arg10[49+map1idx*105],arg21_l[49]);
    atomicAdd(&ind_arg10[50+map1idx*105],arg21_l[50]);
    atomicAdd(&ind_arg10[51+map1idx*105],arg21_l[51]);
    atomicAdd(&ind_arg10[52+map1idx*105],arg21_l[52]);
    atomicAdd(&ind_arg10[53+map1idx*105],arg21_l[53]);
    atomicAdd(&ind_arg10[54+map1idx*105],arg21_l[54]);
    atomicAdd(&ind_arg10[55+map1idx*105],arg21_l[55]);
    atomicAdd(&ind_arg10[56+map1idx*105],arg21_l[56]);
    atomicAdd(&ind_arg10[57+map1idx*105],arg21_l[57]);
    atomicAdd(&ind_arg10[58+map1idx*105],arg21_l[58]);
    atomicAdd(&ind_arg10[59+map1idx*105],arg21_l[59]);
    atomicAdd(&ind_arg10[60+map1idx*105],arg21_l[60]);
    atomicAdd(&ind_arg10[61+map1idx*105],arg21_l[61]);
    atomicAdd(&ind_arg10[62+map1idx*105],arg21_l[62]);
    atomicAdd(&ind_arg10[63+map1idx*105],arg21_l[63]);
    atomicAdd(&ind_arg10[64+map1idx*105],arg21_l[64]);
    atomicAdd(&ind_arg10[65+map1idx*105],arg21_l[65]);
    atomicAdd(&ind_arg10[66+map1idx*105],arg21_l[66]);
    atomicAdd(&ind_arg10[67+map1idx*105],arg21_l[67]);
    atomicAdd(&ind_arg10[68+map1idx*105],arg21_l[68]);
    atomicAdd(&ind_arg10[69+map1idx*105],arg21_l[69]);
    atomicAdd(&ind_arg10[70+map1idx*105],arg21_l[70]);
    atomicAdd(&ind_arg10[71+map1idx*105],arg21_l[71]);
    atomicAdd(&ind_arg10[72+map1idx*105],arg21_l[72]);
    atomicAdd(&ind_arg10[73+map1idx*105],arg21_l[73]);
    atomicAdd(&ind_arg10[74+map1idx*105],arg21_l[74]);
    atomicAdd(&ind_arg10[75+map1idx*105],arg21_l[75]);
    atomicAdd(&ind_arg10[76+map1idx*105],arg21_l[76]);
    atomicAdd(&ind_arg10[77+map1idx*105],arg21_l[77]);
    atomicAdd(&ind_arg10[78+map1idx*105],arg21_l[78]);
    atomicAdd(&ind_arg10[79+map1idx*105],arg21_l[79]);
    atomicAdd(&ind_arg10[80+map1idx*105],arg21_l[80]);
    atomicAdd(&ind_arg10[81+map1idx*105],arg21_l[81]);
    atomicAdd(&ind_arg10[82+map1idx*105],arg21_l[82]);
    atomicAdd(&ind_arg10[83+map1idx*105],arg21_l[83]);
    atomicAdd(&ind_arg10[84+map1idx*105],arg21_l[84]);
    atomicAdd(&ind_arg10[85+map1idx*105],arg21_l[85]);
    atomicAdd(&ind_arg10[86+map1idx*105],arg21_l[86]);
    atomicAdd(&ind_arg10[87+map1idx*105],arg21_l[87]);
    atomicAdd(&ind_arg10[88+map1idx*105],arg21_l[88]);
    atomicAdd(&ind_arg10[89+map1idx*105],arg21_l[89]);
    atomicAdd(&ind_arg10[90+map1idx*105],arg21_l[90]);
    atomicAdd(&ind_arg10[91+map1idx*105],arg21_l[91]);
    atomicAdd(&ind_arg10[92+map1idx*105],arg21_l[92]);
    atomicAdd(&ind_arg10[93+map1idx*105],arg21_l[93]);
    atomicAdd(&ind_arg10[94+map1idx*105],arg21_l[94]);
    atomicAdd(&ind_arg10[95+map1idx*105],arg21_l[95]);
    atomicAdd(&ind_arg10[96+map1idx*105],arg21_l[96]);
    atomicAdd(&ind_arg10[97+map1idx*105],arg21_l[97]);
    atomicAdd(&ind_arg10[98+map1idx*105],arg21_l[98]);
    atomicAdd(&ind_arg10[99+map1idx*105],arg21_l[99]);
    atomicAdd(&ind_arg10[100+map1idx*105],arg21_l[100]);
    atomicAdd(&ind_arg10[101+map1idx*105],arg21_l[101]);
    atomicAdd(&ind_arg10[102+map1idx*105],arg21_l[102]);
    atomicAdd(&ind_arg10[103+map1idx*105],arg21_l[103]);
    atomicAdd(&ind_arg10[104+map1idx*105],arg21_l[104]);
    atomicAdd(&ind_arg10[0+map2idx*105],arg22_l[0]);
    atomicAdd(&ind_arg10[1+map2idx*105],arg22_l[1]);
    atomicAdd(&ind_arg10[2+map2idx*105],arg22_l[2]);
    atomicAdd(&ind_arg10[3+map2idx*105],arg22_l[3]);
    atomicAdd(&ind_arg10[4+map2idx*105],arg22_l[4]);
    atomicAdd(&ind_arg10[5+map2idx*105],arg22_l[5]);
    atomicAdd(&ind_arg10[6+map2idx*105],arg22_l[6]);
    atomicAdd(&ind_arg10[7+map2idx*105],arg22_l[7]);
    atomicAdd(&ind_arg10[8+map2idx*105],arg22_l[8]);
    atomicAdd(&ind_arg10[9+map2idx*105],arg22_l[9]);
    atomicAdd(&ind_arg10[10+map2idx*105],arg22_l[10]);
    atomicAdd(&ind_arg10[11+map2idx*105],arg22_l[11]);
    atomicAdd(&ind_arg10[12+map2idx*105],arg22_l[12]);
    atomicAdd(&ind_arg10[13+map2idx*105],arg22_l[13]);
    atomicAdd(&ind_arg10[14+map2idx*105],arg22_l[14]);
    atomicAdd(&ind_arg10[15+map2idx*105],arg22_l[15]);
    atomicAdd(&ind_arg10[16+map2idx*105],arg22_l[16]);
    atomicAdd(&ind_arg10[17+map2idx*105],arg22_l[17]);
    atomicAdd(&ind_arg10[18+map2idx*105],arg22_l[18]);
    atomicAdd(&ind_arg10[19+map2idx*105],arg22_l[19]);
    atomicAdd(&ind_arg10[20+map2idx*105],arg22_l[20]);
    atomicAdd(&ind_arg10[21+map2idx*105],arg22_l[21]);
    atomicAdd(&ind_arg10[22+map2idx*105],arg22_l[22]);
    atomicAdd(&ind_arg10[23+map2idx*105],arg22_l[23]);
    atomicAdd(&ind_arg10[24+map2idx*105],arg22_l[24]);
    atomicAdd(&ind_arg10[25+map2idx*105],arg22_l[25]);
    atomicAdd(&ind_arg10[26+map2idx*105],arg22_l[26]);
    atomicAdd(&ind_arg10[27+map2idx*105],arg22_l[27]);
    atomicAdd(&ind_arg10[28+map2idx*105],arg22_l[28]);
    atomicAdd(&ind_arg10[29+map2idx*105],arg22_l[29]);
    atomicAdd(&ind_arg10[30+map2idx*105],arg22_l[30]);
    atomicAdd(&ind_arg10[31+map2idx*105],arg22_l[31]);
    atomicAdd(&ind_arg10[32+map2idx*105],arg22_l[32]);
    atomicAdd(&ind_arg10[33+map2idx*105],arg22_l[33]);
    atomicAdd(&ind_arg10[34+map2idx*105],arg22_l[34]);
    atomicAdd(&ind_arg10[35+map2idx*105],arg22_l[35]);
    atomicAdd(&ind_arg10[36+map2idx*105],arg22_l[36]);
    atomicAdd(&ind_arg10[37+map2idx*105],arg22_l[37]);
    atomicAdd(&ind_arg10[38+map2idx*105],arg22_l[38]);
    atomicAdd(&ind_arg10[39+map2idx*105],arg22_l[39]);
    atomicAdd(&ind_arg10[40+map2idx*105],arg22_l[40]);
    atomicAdd(&ind_arg10[41+map2idx*105],arg22_l[41]);
    atomicAdd(&ind_arg10[42+map2idx*105],arg22_l[42]);
    atomicAdd(&ind_arg10[43+map2idx*105],arg22_l[43]);
    atomicAdd(&ind_arg10[44+map2idx*105],arg22_l[44]);
    atomicAdd(&ind_arg10[45+map2idx*105],arg22_l[45]);
    atomicAdd(&ind_arg10[46+map2idx*105],arg22_l[46]);
    atomicAdd(&ind_arg10[47+map2idx*105],arg22_l[47]);
    atomicAdd(&ind_arg10[48+map2idx*105],arg22_l[48]);
    atomicAdd(&ind_arg10[49+map2idx*105],arg22_l[49]);
    atomicAdd(&ind_arg10[50+map2idx*105],arg22_l[50]);
    atomicAdd(&ind_arg10[51+map2idx*105],arg22_l[51]);
    atomicAdd(&ind_arg10[52+map2idx*105],arg22_l[52]);
    atomicAdd(&ind_arg10[53+map2idx*105],arg22_l[53]);
    atomicAdd(&ind_arg10[54+map2idx*105],arg22_l[54]);
    atomicAdd(&ind_arg10[55+map2idx*105],arg22_l[55]);
    atomicAdd(&ind_arg10[56+map2idx*105],arg22_l[56]);
    atomicAdd(&ind_arg10[57+map2idx*105],arg22_l[57]);
    atomicAdd(&ind_arg10[58+map2idx*105],arg22_l[58]);
    atomicAdd(&ind_arg10[59+map2idx*105],arg22_l[59]);
    atomicAdd(&ind_arg10[60+map2idx*105],arg22_l[60]);
    atomicAdd(&ind_arg10[61+map2idx*105],arg22_l[61]);
    atomicAdd(&ind_arg10[62+map2idx*105],arg22_l[62]);
    atomicAdd(&ind_arg10[63+map2idx*105],arg22_l[63]);
    atomicAdd(&ind_arg10[64+map2idx*105],arg22_l[64]);
    atomicAdd(&ind_arg10[65+map2idx*105],arg22_l[65]);
    atomicAdd(&ind_arg10[66+map2idx*105],arg22_l[66]);
    atomicAdd(&ind_arg10[67+map2idx*105],arg22_l[67]);
    atomicAdd(&ind_arg10[68+map2idx*105],arg22_l[68]);
    atomicAdd(&ind_arg10[69+map2idx*105],arg22_l[69]);
    atomicAdd(&ind_arg10[70+map2idx*105],arg22_l[70]);
    atomicAdd(&ind_arg10[71+map2idx*105],arg22_l[71]);
    atomicAdd(&ind_arg10[72+map2idx*105],arg22_l[72]);
    atomicAdd(&ind_arg10[73+map2idx*105],arg22_l[73]);
    atomicAdd(&ind_arg10[74+map2idx*105],arg22_l[74]);
    atomicAdd(&ind_arg10[75+map2idx*105],arg22_l[75]);
    atomicAdd(&ind_arg10[76+map2idx*105],arg22_l[76]);
    atomicAdd(&ind_arg10[77+map2idx*105],arg22_l[77]);
    atomicAdd(&ind_arg10[78+map2idx*105],arg22_l[78]);
    atomicAdd(&ind_arg10[79+map2idx*105],arg22_l[79]);
    atomicAdd(&ind_arg10[80+map2idx*105],arg22_l[80]);
    atomicAdd(&ind_arg10[81+map2idx*105],arg22_l[81]);
    atomicAdd(&ind_arg10[82+map2idx*105],arg22_l[82]);
    atomicAdd(&ind_arg10[83+map2idx*105],arg22_l[83]);
    atomicAdd(&ind_arg10[84+map2idx*105],arg22_l[84]);
    atomicAdd(&ind_arg10[85+map2idx*105],arg22_l[85]);
    atomicAdd(&ind_arg10[86+map2idx*105],arg22_l[86]);
    atomicAdd(&ind_arg10[87+map2idx*105],arg22_l[87]);
    atomicAdd(&ind_arg10[88+map2idx*105],arg22_l[88]);
    atomicAdd(&ind_arg10[89+map2idx*105],arg22_l[89]);
    atomicAdd(&ind_arg10[90+map2idx*105],arg22_l[90]);
    atomicAdd(&ind_arg10[91+map2idx*105],arg22_l[91]);
    atomicAdd(&ind_arg10[92+map2idx*105],arg22_l[92]);
    atomicAdd(&ind_arg10[93+map2idx*105],arg22_l[93]);
    atomicAdd(&ind_arg10[94+map2idx*105],arg22_l[94]);
    atomicAdd(&ind_arg10[95+map2idx*105],arg22_l[95]);
    atomicAdd(&ind_arg10[96+map2idx*105],arg22_l[96]);
    atomicAdd(&ind_arg10[97+map2idx*105],arg22_l[97]);
    atomicAdd(&ind_arg10[98+map2idx*105],arg22_l[98]);
    atomicAdd(&ind_arg10[99+map2idx*105],arg22_l[99]);
    atomicAdd(&ind_arg10[100+map2idx*105],arg22_l[100]);
    atomicAdd(&ind_arg10[101+map2idx*105],arg22_l[101]);
    atomicAdd(&ind_arg10[102+map2idx*105],arg22_l[102]);
    atomicAdd(&ind_arg10[103+map2idx*105],arg22_l[103]);
    atomicAdd(&ind_arg10[104+map2idx*105],arg22_l[104]);
    atomicAdd(&ind_arg11[0+map1idx*105],arg23_l[0]);
    atomicAdd(&ind_arg11[1+map1idx*105],arg23_l[1]);
    atomicAdd(&ind_arg11[2+map1idx*105],arg23_l[2]);
    atomicAdd(&ind_arg11[3+map1idx*105],arg23_l[3]);
    atomicAdd(&ind_arg11[4+map1idx*105],arg23_l[4]);
    atomicAdd(&ind_arg11[5+map1idx*105],arg23_l[5]);
    atomicAdd(&ind_arg11[6+map1idx*105],arg23_l[6]);
    atomicAdd(&ind_arg11[7+map1idx*105],arg23_l[7]);
    atomicAdd(&ind_arg11[8+map1idx*105],arg23_l[8]);
    atomicAdd(&ind_arg11[9+map1idx*105],arg23_l[9]);
    atomicAdd(&ind_arg11[10+map1idx*105],arg23_l[10]);
    atomicAdd(&ind_arg11[11+map1idx*105],arg23_l[11]);
    atomicAdd(&ind_arg11[12+map1idx*105],arg23_l[12]);
    atomicAdd(&ind_arg11[13+map1idx*105],arg23_l[13]);
    atomicAdd(&ind_arg11[14+map1idx*105],arg23_l[14]);
    atomicAdd(&ind_arg11[15+map1idx*105],arg23_l[15]);
    atomicAdd(&ind_arg11[16+map1idx*105],arg23_l[16]);
    atomicAdd(&ind_arg11[17+map1idx*105],arg23_l[17]);
    atomicAdd(&ind_arg11[18+map1idx*105],arg23_l[18]);
    atomicAdd(&ind_arg11[19+map1idx*105],arg23_l[19]);
    atomicAdd(&ind_arg11[20+map1idx*105],arg23_l[20]);
    atomicAdd(&ind_arg11[21+map1idx*105],arg23_l[21]);
    atomicAdd(&ind_arg11[22+map1idx*105],arg23_l[22]);
    atomicAdd(&ind_arg11[23+map1idx*105],arg23_l[23]);
    atomicAdd(&ind_arg11[24+map1idx*105],arg23_l[24]);
    atomicAdd(&ind_arg11[25+map1idx*105],arg23_l[25]);
    atomicAdd(&ind_arg11[26+map1idx*105],arg23_l[26]);
    atomicAdd(&ind_arg11[27+map1idx*105],arg23_l[27]);
    atomicAdd(&ind_arg11[28+map1idx*105],arg23_l[28]);
    atomicAdd(&ind_arg11[29+map1idx*105],arg23_l[29]);
    atomicAdd(&ind_arg11[30+map1idx*105],arg23_l[30]);
    atomicAdd(&ind_arg11[31+map1idx*105],arg23_l[31]);
    atomicAdd(&ind_arg11[32+map1idx*105],arg23_l[32]);
    atomicAdd(&ind_arg11[33+map1idx*105],arg23_l[33]);
    atomicAdd(&ind_arg11[34+map1idx*105],arg23_l[34]);
    atomicAdd(&ind_arg11[35+map1idx*105],arg23_l[35]);
    atomicAdd(&ind_arg11[36+map1idx*105],arg23_l[36]);
    atomicAdd(&ind_arg11[37+map1idx*105],arg23_l[37]);
    atomicAdd(&ind_arg11[38+map1idx*105],arg23_l[38]);
    atomicAdd(&ind_arg11[39+map1idx*105],arg23_l[39]);
    atomicAdd(&ind_arg11[40+map1idx*105],arg23_l[40]);
    atomicAdd(&ind_arg11[41+map1idx*105],arg23_l[41]);
    atomicAdd(&ind_arg11[42+map1idx*105],arg23_l[42]);
    atomicAdd(&ind_arg11[43+map1idx*105],arg23_l[43]);
    atomicAdd(&ind_arg11[44+map1idx*105],arg23_l[44]);
    atomicAdd(&ind_arg11[45+map1idx*105],arg23_l[45]);
    atomicAdd(&ind_arg11[46+map1idx*105],arg23_l[46]);
    atomicAdd(&ind_arg11[47+map1idx*105],arg23_l[47]);
    atomicAdd(&ind_arg11[48+map1idx*105],arg23_l[48]);
    atomicAdd(&ind_arg11[49+map1idx*105],arg23_l[49]);
    atomicAdd(&ind_arg11[50+map1idx*105],arg23_l[50]);
    atomicAdd(&ind_arg11[51+map1idx*105],arg23_l[51]);
    atomicAdd(&ind_arg11[52+map1idx*105],arg23_l[52]);
    atomicAdd(&ind_arg11[53+map1idx*105],arg23_l[53]);
    atomicAdd(&ind_arg11[54+map1idx*105],arg23_l[54]);
    atomicAdd(&ind_arg11[55+map1idx*105],arg23_l[55]);
    atomicAdd(&ind_arg11[56+map1idx*105],arg23_l[56]);
    atomicAdd(&ind_arg11[57+map1idx*105],arg23_l[57]);
    atomicAdd(&ind_arg11[58+map1idx*105],arg23_l[58]);
    atomicAdd(&ind_arg11[59+map1idx*105],arg23_l[59]);
    atomicAdd(&ind_arg11[60+map1idx*105],arg23_l[60]);
    atomicAdd(&ind_arg11[61+map1idx*105],arg23_l[61]);
    atomicAdd(&ind_arg11[62+map1idx*105],arg23_l[62]);
    atomicAdd(&ind_arg11[63+map1idx*105],arg23_l[63]);
    atomicAdd(&ind_arg11[64+map1idx*105],arg23_l[64]);
    atomicAdd(&ind_arg11[65+map1idx*105],arg23_l[65]);
    atomicAdd(&ind_arg11[66+map1idx*105],arg23_l[66]);
    atomicAdd(&ind_arg11[67+map1idx*105],arg23_l[67]);
    atomicAdd(&ind_arg11[68+map1idx*105],arg23_l[68]);
    atomicAdd(&ind_arg11[69+map1idx*105],arg23_l[69]);
    atomicAdd(&ind_arg11[70+map1idx*105],arg23_l[70]);
    atomicAdd(&ind_arg11[71+map1idx*105],arg23_l[71]);
    atomicAdd(&ind_arg11[72+map1idx*105],arg23_l[72]);
    atomicAdd(&ind_arg11[73+map1idx*105],arg23_l[73]);
    atomicAdd(&ind_arg11[74+map1idx*105],arg23_l[74]);
    atomicAdd(&ind_arg11[75+map1idx*105],arg23_l[75]);
    atomicAdd(&ind_arg11[76+map1idx*105],arg23_l[76]);
    atomicAdd(&ind_arg11[77+map1idx*105],arg23_l[77]);
    atomicAdd(&ind_arg11[78+map1idx*105],arg23_l[78]);
    atomicAdd(&ind_arg11[79+map1idx*105],arg23_l[79]);
    atomicAdd(&ind_arg11[80+map1idx*105],arg23_l[80]);
    atomicAdd(&ind_arg11[81+map1idx*105],arg23_l[81]);
    atomicAdd(&ind_arg11[82+map1idx*105],arg23_l[82]);
    atomicAdd(&ind_arg11[83+map1idx*105],arg23_l[83]);
    atomicAdd(&ind_arg11[84+map1idx*105],arg23_l[84]);
    atomicAdd(&ind_arg11[85+map1idx*105],arg23_l[85]);
    atomicAdd(&ind_arg11[86+map1idx*105],arg23_l[86]);
    atomicAdd(&ind_arg11[87+map1idx*105],arg23_l[87]);
    atomicAdd(&ind_arg11[88+map1idx*105],arg23_l[88]);
    atomicAdd(&ind_arg11[89+map1idx*105],arg23_l[89]);
    atomicAdd(&ind_arg11[90+map1idx*105],arg23_l[90]);
    atomicAdd(&ind_arg11[91+map1idx*105],arg23_l[91]);
    atomicAdd(&ind_arg11[92+map1idx*105],arg23_l[92]);
    atomicAdd(&ind_arg11[93+map1idx*105],arg23_l[93]);
    atomicAdd(&ind_arg11[94+map1idx*105],arg23_l[94]);
    atomicAdd(&ind_arg11[95+map1idx*105],arg23_l[95]);
    atomicAdd(&ind_arg11[96+map1idx*105],arg23_l[96]);
    atomicAdd(&ind_arg11[97+map1idx*105],arg23_l[97]);
    atomicAdd(&ind_arg11[98+map1idx*105],arg23_l[98]);
    atomicAdd(&ind_arg11[99+map1idx*105],arg23_l[99]);
    atomicAdd(&ind_arg11[100+map1idx*105],arg23_l[100]);
    atomicAdd(&ind_arg11[101+map1idx*105],arg23_l[101]);
    atomicAdd(&ind_arg11[102+map1idx*105],arg23_l[102]);
    atomicAdd(&ind_arg11[103+map1idx*105],arg23_l[103]);
    atomicAdd(&ind_arg11[104+map1idx*105],arg23_l[104]);
    atomicAdd(&ind_arg11[0+map2idx*105],arg24_l[0]);
    atomicAdd(&ind_arg11[1+map2idx*105],arg24_l[1]);
    atomicAdd(&ind_arg11[2+map2idx*105],arg24_l[2]);
    atomicAdd(&ind_arg11[3+map2idx*105],arg24_l[3]);
    atomicAdd(&ind_arg11[4+map2idx*105],arg24_l[4]);
    atomicAdd(&ind_arg11[5+map2idx*105],arg24_l[5]);
    atomicAdd(&ind_arg11[6+map2idx*105],arg24_l[6]);
    atomicAdd(&ind_arg11[7+map2idx*105],arg24_l[7]);
    atomicAdd(&ind_arg11[8+map2idx*105],arg24_l[8]);
    atomicAdd(&ind_arg11[9+map2idx*105],arg24_l[9]);
    atomicAdd(&ind_arg11[10+map2idx*105],arg24_l[10]);
    atomicAdd(&ind_arg11[11+map2idx*105],arg24_l[11]);
    atomicAdd(&ind_arg11[12+map2idx*105],arg24_l[12]);
    atomicAdd(&ind_arg11[13+map2idx*105],arg24_l[13]);
    atomicAdd(&ind_arg11[14+map2idx*105],arg24_l[14]);
    atomicAdd(&ind_arg11[15+map2idx*105],arg24_l[15]);
    atomicAdd(&ind_arg11[16+map2idx*105],arg24_l[16]);
    atomicAdd(&ind_arg11[17+map2idx*105],arg24_l[17]);
    atomicAdd(&ind_arg11[18+map2idx*105],arg24_l[18]);
    atomicAdd(&ind_arg11[19+map2idx*105],arg24_l[19]);
    atomicAdd(&ind_arg11[20+map2idx*105],arg24_l[20]);
    atomicAdd(&ind_arg11[21+map2idx*105],arg24_l[21]);
    atomicAdd(&ind_arg11[22+map2idx*105],arg24_l[22]);
    atomicAdd(&ind_arg11[23+map2idx*105],arg24_l[23]);
    atomicAdd(&ind_arg11[24+map2idx*105],arg24_l[24]);
    atomicAdd(&ind_arg11[25+map2idx*105],arg24_l[25]);
    atomicAdd(&ind_arg11[26+map2idx*105],arg24_l[26]);
    atomicAdd(&ind_arg11[27+map2idx*105],arg24_l[27]);
    atomicAdd(&ind_arg11[28+map2idx*105],arg24_l[28]);
    atomicAdd(&ind_arg11[29+map2idx*105],arg24_l[29]);
    atomicAdd(&ind_arg11[30+map2idx*105],arg24_l[30]);
    atomicAdd(&ind_arg11[31+map2idx*105],arg24_l[31]);
    atomicAdd(&ind_arg11[32+map2idx*105],arg24_l[32]);
    atomicAdd(&ind_arg11[33+map2idx*105],arg24_l[33]);
    atomicAdd(&ind_arg11[34+map2idx*105],arg24_l[34]);
    atomicAdd(&ind_arg11[35+map2idx*105],arg24_l[35]);
    atomicAdd(&ind_arg11[36+map2idx*105],arg24_l[36]);
    atomicAdd(&ind_arg11[37+map2idx*105],arg24_l[37]);
    atomicAdd(&ind_arg11[38+map2idx*105],arg24_l[38]);
    atomicAdd(&ind_arg11[39+map2idx*105],arg24_l[39]);
    atomicAdd(&ind_arg11[40+map2idx*105],arg24_l[40]);
    atomicAdd(&ind_arg11[41+map2idx*105],arg24_l[41]);
    atomicAdd(&ind_arg11[42+map2idx*105],arg24_l[42]);
    atomicAdd(&ind_arg11[43+map2idx*105],arg24_l[43]);
    atomicAdd(&ind_arg11[44+map2idx*105],arg24_l[44]);
    atomicAdd(&ind_arg11[45+map2idx*105],arg24_l[45]);
    atomicAdd(&ind_arg11[46+map2idx*105],arg24_l[46]);
    atomicAdd(&ind_arg11[47+map2idx*105],arg24_l[47]);
    atomicAdd(&ind_arg11[48+map2idx*105],arg24_l[48]);
    atomicAdd(&ind_arg11[49+map2idx*105],arg24_l[49]);
    atomicAdd(&ind_arg11[50+map2idx*105],arg24_l[50]);
    atomicAdd(&ind_arg11[51+map2idx*105],arg24_l[51]);
    atomicAdd(&ind_arg11[52+map2idx*105],arg24_l[52]);
    atomicAdd(&ind_arg11[53+map2idx*105],arg24_l[53]);
    atomicAdd(&ind_arg11[54+map2idx*105],arg24_l[54]);
    atomicAdd(&ind_arg11[55+map2idx*105],arg24_l[55]);
    atomicAdd(&ind_arg11[56+map2idx*105],arg24_l[56]);
    atomicAdd(&ind_arg11[57+map2idx*105],arg24_l[57]);
    atomicAdd(&ind_arg11[58+map2idx*105],arg24_l[58]);
    atomicAdd(&ind_arg11[59+map2idx*105],arg24_l[59]);
    atomicAdd(&ind_arg11[60+map2idx*105],arg24_l[60]);
    atomicAdd(&ind_arg11[61+map2idx*105],arg24_l[61]);
    atomicAdd(&ind_arg11[62+map2idx*105],arg24_l[62]);
    atomicAdd(&ind_arg11[63+map2idx*105],arg24_l[63]);
    atomicAdd(&ind_arg11[64+map2idx*105],arg24_l[64]);
    atomicAdd(&ind_arg11[65+map2idx*105],arg24_l[65]);
    atomicAdd(&ind_arg11[66+map2idx*105],arg24_l[66]);
    atomicAdd(&ind_arg11[67+map2idx*105],arg24_l[67]);
    atomicAdd(&ind_arg11[68+map2idx*105],arg24_l[68]);
    atomicAdd(&ind_arg11[69+map2idx*105],arg24_l[69]);
    atomicAdd(&ind_arg11[70+map2idx*105],arg24_l[70]);
    atomicAdd(&ind_arg11[71+map2idx*105],arg24_l[71]);
    atomicAdd(&ind_arg11[72+map2idx*105],arg24_l[72]);
    atomicAdd(&ind_arg11[73+map2idx*105],arg24_l[73]);
    atomicAdd(&ind_arg11[74+map2idx*105],arg24_l[74]);
    atomicAdd(&ind_arg11[75+map2idx*105],arg24_l[75]);
    atomicAdd(&ind_arg11[76+map2idx*105],arg24_l[76]);
    atomicAdd(&ind_arg11[77+map2idx*105],arg24_l[77]);
    atomicAdd(&ind_arg11[78+map2idx*105],arg24_l[78]);
    atomicAdd(&ind_arg11[79+map2idx*105],arg24_l[79]);
    atomicAdd(&ind_arg11[80+map2idx*105],arg24_l[80]);
    atomicAdd(&ind_arg11[81+map2idx*105],arg24_l[81]);
    atomicAdd(&ind_arg11[82+map2idx*105],arg24_l[82]);
    atomicAdd(&ind_arg11[83+map2idx*105],arg24_l[83]);
    atomicAdd(&ind_arg11[84+map2idx*105],arg24_l[84]);
    atomicAdd(&ind_arg11[85+map2idx*105],arg24_l[85]);
    atomicAdd(&ind_arg11[86+map2idx*105],arg24_l[86]);
    atomicAdd(&ind_arg11[87+map2idx*105],arg24_l[87]);
    atomicAdd(&ind_arg11[88+map2idx*105],arg24_l[88]);
    atomicAdd(&ind_arg11[89+map2idx*105],arg24_l[89]);
    atomicAdd(&ind_arg11[90+map2idx*105],arg24_l[90]);
    atomicAdd(&ind_arg11[91+map2idx*105],arg24_l[91]);
    atomicAdd(&ind_arg11[92+map2idx*105],arg24_l[92]);
    atomicAdd(&ind_arg11[93+map2idx*105],arg24_l[93]);
    atomicAdd(&ind_arg11[94+map2idx*105],arg24_l[94]);
    atomicAdd(&ind_arg11[95+map2idx*105],arg24_l[95]);
    atomicAdd(&ind_arg11[96+map2idx*105],arg24_l[96]);
    atomicAdd(&ind_arg11[97+map2idx*105],arg24_l[97]);
    atomicAdd(&ind_arg11[98+map2idx*105],arg24_l[98]);
    atomicAdd(&ind_arg11[99+map2idx*105],arg24_l[99]);
    atomicAdd(&ind_arg11[100+map2idx*105],arg24_l[100]);
    atomicAdd(&ind_arg11[101+map2idx*105],arg24_l[101]);
    atomicAdd(&ind_arg11[102+map2idx*105],arg24_l[102]);
    atomicAdd(&ind_arg11[103+map2idx*105],arg24_l[103]);
    atomicAdd(&ind_arg11[104+map2idx*105],arg24_l[104]);
  }
}


//host stub function
void op_par_loop_gauss_grad_faces(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg3,
  op_arg arg5,
  op_arg arg7,
  op_arg arg9,
  op_arg arg11,
  op_arg arg13,
  op_arg arg15,
  op_arg arg17,
  op_arg arg19,
  op_arg arg21,
  op_arg arg23){

  int nargs = 25;
  op_arg args[25];

  args[0] = arg0;
  arg1.idx = 0;
  args[1] = arg1;
  for ( int v=1; v<2; v++ ){
    args[1 + v] = op_arg_dat(arg1.dat, v, arg1.map, 105, "double", OP_READ);
  }

  arg3.idx = 0;
  args[3] = arg3;
  for ( int v=1; v<2; v++ ){
    args[3 + v] = op_arg_dat(arg3.dat, v, arg3.map, 105, "double", OP_READ);
  }

  arg5.idx = 0;
  args[5] = arg5;
  for ( int v=1; v<2; v++ ){
    args[5 + v] = op_arg_dat(arg5.dat, v, arg5.map, 105, "double", OP_READ);
  }

  arg7.idx = 0;
  args[7] = arg7;
  for ( int v=1; v<2; v++ ){
    args[7 + v] = op_arg_dat(arg7.dat, v, arg7.map, 105, "double", OP_READ);
  }

  arg9.idx = 0;
  args[9] = arg9;
  for ( int v=1; v<2; v++ ){
    args[9 + v] = op_arg_dat(arg9.dat, v, arg9.map, 105, "double", OP_READ);
  }

  arg11.idx = 0;
  args[11] = arg11;
  for ( int v=1; v<2; v++ ){
    args[11 + v] = op_arg_dat(arg11.dat, v, arg11.map, 105, "double", OP_READ);
  }

  arg13.idx = 0;
  args[13] = arg13;
  for ( int v=1; v<2; v++ ){
    args[13 + v] = op_arg_dat(arg13.dat, v, arg13.map, 105, "double", OP_INC);
  }

  arg15.idx = 0;
  args[15] = arg15;
  for ( int v=1; v<2; v++ ){
    args[15 + v] = op_arg_dat(arg15.dat, v, arg15.map, 105, "double", OP_INC);
  }

  arg17.idx = 0;
  args[17] = arg17;
  for ( int v=1; v<2; v++ ){
    args[17 + v] = op_arg_dat(arg17.dat, v, arg17.map, 105, "double", OP_INC);
  }

  arg19.idx = 0;
  args[19] = arg19;
  for ( int v=1; v<2; v++ ){
    args[19 + v] = op_arg_dat(arg19.dat, v, arg19.map, 105, "double", OP_INC);
  }

  arg21.idx = 0;
  args[21] = arg21;
  for ( int v=1; v<2; v++ ){
    args[21 + v] = op_arg_dat(arg21.dat, v, arg21.map, 105, "double", OP_INC);
  }

  arg23.idx = 0;
  args[23] = arg23;
  for ( int v=1; v<2; v++ ){
    args[23 + v] = op_arg_dat(arg23.dat, v, arg23.map, 105, "double", OP_INC);
  }


  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(25);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[25].name      = name;
  OP_kernels[25].count    += 1;


  int    ninds   = 12;
  int    inds[25] = {-1,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11};

  if (OP_diags>2) {
    printf(" kernel routine with indirection: gauss_grad_faces\n");
  }
  int set_size = op_mpi_halo_exchanges_cuda(set, nargs, args);
  if (set_size > 0) {

    //set CUDA execution parameters
    #ifdef OP_BLOCK_SIZE_25
      int nthread = OP_BLOCK_SIZE_25;
    #else
      int nthread = OP_block_size;
    #endif

    for ( int round=0; round<2; round++ ){
      if (round==1) {
        op_mpi_wait_all_cuda(nargs, args);
      }
      int start = round==0 ? 0 : set->core_size;
      int end = round==0 ? set->core_size : set->size + set->exec_size;
      if (end-start>0) {
        int nblocks = (end-start-1)/nthread+1;
        op_cuda_gauss_grad_faces<<<nblocks,nthread>>>(
        (double *)arg1.data_d,
        (double *)arg3.data_d,
        (double *)arg5.data_d,
        (double *)arg7.data_d,
        (double *)arg9.data_d,
        (double *)arg11.data_d,
        (double *)arg13.data_d,
        (double *)arg15.data_d,
        (double *)arg17.data_d,
        (double *)arg19.data_d,
        (double *)arg21.data_d,
        (double *)arg23.data_d,
        arg1.map_data_d,
        (int*)arg0.data_d,
        start,end,set->size+set->exec_size);
      }
    }
  }
  op_mpi_set_dirtybit_cuda(nargs, args);
  cutilSafeCall(cudaDeviceSynchronize());
  //update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[25].time     += wall_t2 - wall_t1;
}
