//
// auto-generated by op2.py
//

// header
#include "op_lib_cpp.h"

// user kernel files
#include "init_grid_omp4kernel.cpp"
#include "set_ic1_omp4kernel.cpp"
#include "set_ic2_omp4kernel.cpp"
#include "div_omp4kernel.cpp"
#include "curl_omp4kernel.cpp"
#include "grad_omp4kernel.cpp"
#include "pRHS_faces_omp4kernel.cpp"
#include "pRHS_bc_omp4kernel.cpp"
#include "pRHS_du_omp4kernel.cpp"
#include "pRHS_fluxq_omp4kernel.cpp"
#include "pRHS_J_omp4kernel.cpp"
