//
// auto-generated by op2.py
//

#ifdef _OPENMP
  #include <omp.h>
#endif

// global constants
extern double gam;
extern double mu;
extern double nu;
extern double bc_mach;
extern double bc_alpha;
extern double bc_p;
extern double bc_u;
extern double bc_v;
extern int FMASK[15];
extern double ic_u;
extern double ic_v;

// header
#include "op_lib_cpp.h"

// user kernel files
#include "init_grid_kernel.cpp"
#include "set_ic_kernel.cpp"
#include "calc_dt_kernel.cpp"
#include "advection_flux_kernel.cpp"
#include "advection_faces_kernel.cpp"
#include "advection_bc_kernel.cpp"
#include "advection_numerical_flux_kernel.cpp"
#include "advection_intermediate_vel_kernel.cpp"
#include "pressure_bc_kernel.cpp"
#include "pressure_rhs_kernel.cpp"
#include "pressure_bc2_kernel.cpp"
#include "pressure_bc3_kernel.cpp"
#include "pressure_update_vel_kernel.cpp"
#include "viscosity_faces_kernel.cpp"
#include "viscosity_set_bc_kernel.cpp"
#include "viscosity_rhs_kernel.cpp"
#include "viscosity_bc_kernel.cpp"
#include "setup_poisson_kernel.cpp"
#include "set_tau_kernel.cpp"
#include "set_tau_bc_kernel.cpp"
#include "poisson_rhs_faces_kernel.cpp"
#include "poisson_rhs_bc_kernel.cpp"
#include "poisson_rhs_du_kernel.cpp"
#include "poisson_rhs_qbc_kernel.cpp"
#include "poisson_rhs_fluxq_kernel.cpp"
#include "poisson_rhs_J_kernel.cpp"
#include "div_kernel.cpp"
#include "curl_kernel.cpp"
#include "grad_kernel.cpp"
#include "poisson_test_init_kernel.cpp"
#include "poisson_test_bc_kernel.cpp"
#include "poisson_test_set_rhs_kernel.cpp"
#include "poisson_test_error_kernel.cpp"
