//
// auto-generated by op2.py
//

//global constants
#ifndef MAX_CONST_SIZE
#define MAX_CONST_SIZE 128
#endif

__constant__ int FMASK_cuda[15];

//header
#include "op_lib_cpp.h"
#include "op_cuda_rt_support.h"
#include "op_cuda_reduction.h"

void op_decl_const_char(int dim, char const *type,
int size, char *dat, char const *name){
  if (!OP_hybrid_gpu) return;
  if (!strcmp(name,"FMASK")) {
    cutilSafeCall(cudaMemcpyToSymbol(FMASK_cuda, dat, dim*size));
  }
  else
  {
    printf("error: unknown const name\n"); exit(1);
  }
}

//user kernel files
#include "init_grid_kernel.cu"
#include "set_ic1_kernel.cu"
#include "set_tau_kernel.cu"
#include "set_tau_bc_kernel.cu"
#include "set_ic2_kernel.cu"
#include "set_rhs_kernel.cu"
#include "calc_sol_kernel.cu"
#include "div_kernel.cu"
#include "curl_kernel.cu"
#include "grad_kernel.cu"
#include "pRHS_faces_kernel.cu"
#include "pRHS_bc_kernel.cu"
#include "pRHS_du_kernel.cu"
#include "pRHS_fluxq_kernel.cu"
#include "pRHS_J_kernel.cu"
